
    // ============================================================
    // LEVEL 0: L3 Cache Tiling [256, 256, 256]
    // Working set: ~768 KB (fits comfortably in 33 MB L3)
    // Purpose: Thread-level parallelism, minimize cross-core traffic
    // ============================================================

    // ============================================================
    // LEVEL 1: L2 Cache Tiling [128, 128, 64]
    // Working set: ~80 KB (fits in 2.5 MB L2)
    // Purpose: Core-level optimization, good balance
    // ============================================================

    // ============================================================
    // LEVEL 2: L1 Cache Tiling [32, 32, 16]
    // Working set: ~20 KB (fits in 38 KB L1d)
    // Purpose: Minimize L1 cache misses, prepare for SIMD
    // ============================================================



module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%root: !transform.any_op {transform.readonly}) {

    
    // Match linalg.matmul (named op, before generalization)
    %matmuls = transform.structured.match ops{["linalg.matmul"]} in %root 
        : (!transform.any_op) -> !transform.any_op
    
    %tiled_l3, %loops_l3:3 = transform.structured.tile_using_for %matmuls 
        tile_sizes [256, 256, 256]
        : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    

    %tiled_l2, %loops_l2:3 = transform.structured.tile_using_for %tiled_l3 
        tile_sizes [128, 128, 64]
        : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    

    %tiled_l1, %loops_l1:3 = transform.structured.tile_using_for %tiled_l2 
        tile_sizes [32, 32, 16]
        : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    

    %tiled_reg, %loops_reg:3 = transform.structured.tile_using_for %tiled_l1 
        tile_sizes [8, 8, 1]
        : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    
    // ============================================================
    // PADDING - Currently disabled due to dialect dependencies
    // ============================================================
    // NOTE: Padding requires bufferization dialect to be loaded
    // For now, ensure matrix sizes are multiples of tile sizes:
    //   - L3: multiples of 256
    //   - L2: multiples of 128  
    //   - L1: multiples of 32
    //   - Register: multiples of 8
    //
    // Alternative: Use dynamic tile sizes with min() operations
    // which are automatically generated by tile_using_for
    //
    // Future: Enable padding by loading bufferization dialect in pipeline
    
    transform.yield
  }
}
