; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"

%0 = type { float, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64 }
%1 = type { ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, i64, i64, i64 }
%2 = type { ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, float, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64 }

@main_kernel_binary = internal constant [782 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main_kernel\0A\0A.visible .entry main_kernel(\0A\09.param .f32 main_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_1,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_2,\0A\09.param .u64 main_kernel_param_3,\0A\09.param .u64 main_kernel_param_4,\0A\09.param .u64 main_kernel_param_5,\0A\09.param .u64 main_kernel_param_6,\0A\09.param .u64 main_kernel_param_7\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<5>;\0A\09.reg .b64 \09%rd<4>;\0A\0A\09ld.param.b32 \09%r1, [main_kernel_param_0];\0A\09mov.u32 \09%r2, %ctaid.x;\0A\09ld.param.b64 \09%rd1, [main_kernel_param_2];\0A\09mov.u32 \09%r3, %ctaid.y;\0A\09mad.lo.s32 \09%r4, %r2, 10, %r3;\0A\09mul.wide.u32 \09%rd2, %r4, 4;\0A\09add.s64 \09%rd3, %rd1, %rd2;\0A\09st.global.b32 \09[%rd3], %r1;\0A\09ret;\0A\0A}\0A\00", align 8
@main_kernel_module = internal global ptr null
@main_kernel_0_binary = internal constant [2304 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main_kernel\0A\0A.visible .entry main_kernel(\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_1,\0A\09.param .u64 main_kernel_param_2,\0A\09.param .u64 main_kernel_param_3,\0A\09.param .u64 main_kernel_param_4,\0A\09.param .u64 main_kernel_param_5,\0A\09.param .u64 main_kernel_param_6,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_7,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_8,\0A\09.param .u64 main_kernel_param_9,\0A\09.param .u64 main_kernel_param_10,\0A\09.param .u64 main_kernel_param_11,\0A\09.param .u64 main_kernel_param_12,\0A\09.param .u64 main_kernel_param_13,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_14,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_15,\0A\09.param .u64 main_kernel_param_16,\0A\09.param .u64 main_kernel_param_17,\0A\09.param .u64 main_kernel_param_18,\0A\09.param .u64 main_kernel_param_19,\0A\09.param .u64 main_kernel_param_20,\0A\09.param .u64 main_kernel_param_21,\0A\09.param .u64 main_kernel_param_22,\0A\09.param .u64 main_kernel_param_23\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .pred \09%p<3>;\0A\09.reg .b32 \09%r<10>;\0A\09.reg .b64 \09%rd<29>;\0A\0A\09ld.param.b64 \09%rd17, [main_kernel_param_22];\0A\09ld.param.b64 \09%rd28, [main_kernel_param_21];\0A\09setp.ge.s64 \09%p1, %rd28, %rd17;\0A\09@%p1 bra \09$L__BB0_3;\0A\09ld.param.b64 \09%rd18, [main_kernel_param_23];\0A\09ld.param.b64 \09%rd15, [main_kernel_param_15];\0A\09ld.param.b64 \09%rd14, [main_kernel_param_8];\0A\09ld.param.b64 \09%rd13, [main_kernel_param_1];\0A\09mov.u32 \09%r4, %ctaid.y;\0A\09cvt.u64.u32 \09%rd1, %r4;\0A\09shl.b64 \09%rd19, %rd1, 2;\0A\09add.s64 \09%rd20, %rd15, %rd19;\0A\09mov.u32 \09%r5, %ctaid.x;\0A\09mul.wide.u32 \09%rd21, %r5, 64;\0A\09mul.wide.u32 \09%rd22, %r5, 40;\0A\09add.s64 \09%rd2, %rd20, %rd22;\0A\09ld.global.b32 \09%r9, [%rd2];\0A\09shl.b64 \09%rd23, %rd28, 2;\0A\09add.s64 \09%rd24, %rd21, %rd23;\0A\09add.s64 \09%rd27, %rd13, %rd24;\0A\09shl.b64 \09%rd4, %rd18, 2;\0A\09mad.lo.s64 \09%rd25, %rd28, 40, %rd19;\0A\09add.s64 \09%rd26, %rd14, %rd25;\0A\09mul.lo.s64 \09%rd6, %rd18, 40;\0A$L__BB0_2:\0A\09ld.global.b32 \09%r6, [%rd27];\0A\09ld.global.b32 \09%r7, [%rd26];\0A\09mul.rn.f32 \09%r8, %r6, %r7;\0A\09add.rn.f32 \09%r9, %r9, %r8;\0A\09st.global.b32 \09[%rd2], %r9;\0A\09add.s64 \09%rd28, %rd28, %rd18;\0A\09add.s64 \09%rd27, %rd27, %rd4;\0A\09add.s64 \09%rd26, %rd26, %rd6;\0A\09setp.lt.s64 \09%p2, %rd28, %rd17;\0A\09@%p2 bra \09$L__BB0_2;\0A$L__BB0_3:\0A\09ret;\0A\0A}\0A\00", align 8
@main_kernel_0_module = internal global ptr null
@main_kernel_1_binary = internal constant [1578 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main_kernel\0A\0A.visible .entry main_kernel(\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_1,\0A\09.param .u64 main_kernel_param_2,\0A\09.param .u64 main_kernel_param_3,\0A\09.param .u64 main_kernel_param_4,\0A\09.param .u64 main_kernel_param_5,\0A\09.param .u64 main_kernel_param_6,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_7,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_8,\0A\09.param .u64 main_kernel_param_9,\0A\09.param .u64 main_kernel_param_10,\0A\09.param .u64 main_kernel_param_11,\0A\09.param .f32 main_kernel_param_12,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_13,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_14,\0A\09.param .u64 main_kernel_param_15,\0A\09.param .u64 main_kernel_param_16,\0A\09.param .u64 main_kernel_param_17,\0A\09.param .u64 main_kernel_param_18,\0A\09.param .u64 main_kernel_param_19\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<9>;\0A\09.reg .b64 \09%rd<9>;\0A\0A\09ld.param.b64 \09%rd1, [main_kernel_param_1];\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09mov.u32 \09%r2, %ctaid.y;\0A\09mad.lo.s32 \09%r3, %r1, 10, %r2;\0A\09mul.wide.u32 \09%rd2, %r3, 4;\0A\09add.s64 \09%rd3, %rd1, %rd2;\0A\09ld.global.b32 \09%r4, [%rd3];\0A\09ld.param.b64 \09%rd4, [main_kernel_param_8];\0A\09mul.wide.u32 \09%rd5, %r2, 4;\0A\09add.s64 \09%rd6, %rd4, %rd5;\0A\09ld.global.b32 \09%r5, [%rd6];\0A\09add.rn.f32 \09%r6, %r4, %r5;\0A\09ld.param.b32 \09%r7, [main_kernel_param_12];\0A\09max.NaN.f32 \09%r8, %r6, %r7;\0A\09ld.param.b64 \09%rd7, [main_kernel_param_14];\0A\09add.s64 \09%rd8, %rd7, %rd2;\0A\09st.global.b32 \09[%rd8], %r8;\0A\09ret;\0A\0A}\0A\00", align 8
@main_kernel_1_module = internal global ptr null
@llvm.global_ctors = appending global [3 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 123, ptr @main_kernel_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main_kernel_0_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main_kernel_1_load, ptr null }]
@llvm.global_dtors = appending global [3 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 123, ptr @main_kernel_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main_kernel_0_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main_kernel_1_unload, ptr null }]
@main_kernel_main_kernel_name = private unnamed_addr constant [12 x i8] c"main_kernel\00", align 1
@main_kernel_0_main_kernel_name = private unnamed_addr constant [12 x i8] c"main_kernel\00", align 1
@main_kernel_1_main_kernel_name = private unnamed_addr constant [12 x i8] c"main_kernel\00", align 1

declare i32 @cudaMalloc(ptr, i64)

declare i32 @cudaMemcpy(ptr, ptr, i64, i32)

declare i32 @cudaFree(ptr)

define { ptr, ptr, i64, [2 x i64], [2 x i64] } @main(ptr %0, ptr %1, i64 %2, i64 %3, i64 %4, i64 %5, i64 %6, ptr %7, ptr %8, i64 %9, i64 %10, i64 %11, i64 %12, i64 %13, ptr %14, ptr %15, i64 %16, i64 %17, i64 %18, i64 %19, i64 %20) {
  %22 = alloca ptr addrspace(1), align 8
  %23 = call i32 @cudaMalloc(ptr %22, i64 640)
  %24 = load ptr addrspace(1), ptr %22, align 8
  %25 = addrspacecast ptr addrspace(1) %24 to ptr
  %26 = call i32 @cudaMemcpy(ptr %25, ptr %8, i64 640, i32 4)
  %27 = alloca ptr addrspace(1), align 8
  %28 = call i32 @cudaMalloc(ptr %27, i64 512)
  %29 = load ptr addrspace(1), ptr %27, align 8
  %30 = addrspacecast ptr addrspace(1) %29 to ptr
  %31 = call i32 @cudaMemcpy(ptr %30, ptr %1, i64 512, i32 4)
  %32 = alloca ptr addrspace(1), align 8
  %33 = call i32 @cudaMalloc(ptr %32, i64 40)
  %34 = load ptr addrspace(1), ptr %32, align 8
  %35 = addrspacecast ptr addrspace(1) %34 to ptr
  %36 = call i32 @cudaMemcpy(ptr %35, ptr %15, i64 40, i32 4)
  %37 = alloca ptr, align 8
  %38 = call i32 @cudaMalloc(ptr %37, i64 320)
  %39 = load ptr, ptr %37, align 8
  %40 = alloca ptr addrspace(1), align 8
  %41 = call i32 @cudaMalloc(ptr %40, i64 320)
  %42 = load ptr addrspace(1), ptr %40, align 8
  %43 = addrspacecast ptr addrspace(1) %42 to ptr
  %44 = call i32 @cudaMemcpy(ptr %43, ptr %39, i64 320, i32 4)
  %45 = alloca %0, align 8
  %46 = alloca ptr, i64 8, align 8
  %47 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 0
  store float 0.000000e+00, ptr %47, align 4
  %48 = getelementptr ptr, ptr %46, i32 0
  store ptr %47, ptr %48, align 8
  %49 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 1
  store ptr addrspace(1) %42, ptr %49, align 8
  %50 = getelementptr ptr, ptr %46, i32 1
  store ptr %49, ptr %50, align 8
  %51 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 2
  store ptr addrspace(1) %42, ptr %51, align 8
  %52 = getelementptr ptr, ptr %46, i32 2
  store ptr %51, ptr %52, align 8
  %53 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 3
  store i64 0, ptr %53, align 4
  %54 = getelementptr ptr, ptr %46, i32 3
  store ptr %53, ptr %54, align 8
  %55 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 4
  store i64 8, ptr %55, align 4
  %56 = getelementptr ptr, ptr %46, i32 4
  store ptr %55, ptr %56, align 8
  %57 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 5
  store i64 10, ptr %57, align 4
  %58 = getelementptr ptr, ptr %46, i32 5
  store ptr %57, ptr %58, align 8
  %59 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 6
  store i64 10, ptr %59, align 4
  %60 = getelementptr ptr, ptr %46, i32 6
  store ptr %59, ptr %60, align 8
  %61 = getelementptr inbounds nuw %0, ptr %45, i32 0, i32 7
  store i64 1, ptr %61, align 4
  %62 = getelementptr ptr, ptr %46, i32 7
  store ptr %61, ptr %62, align 8
  %63 = load ptr, ptr @main_kernel_module, align 8
  %64 = call ptr @mgpuModuleGetFunction(ptr %63, ptr @main_kernel_main_kernel_name)
  %65 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %64, i64 8, i64 10, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %65, ptr %46, ptr null, i64 8)
  call void @mgpuStreamSynchronize(ptr %65)
  call void @mgpuStreamDestroy(ptr %65)
  %66 = alloca %1, align 8
  %67 = alloca ptr, i64 24, align 8
  %68 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 0
  store ptr addrspace(1) %29, ptr %68, align 8
  %69 = getelementptr ptr, ptr %67, i32 0
  store ptr %68, ptr %69, align 8
  %70 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 1
  store ptr addrspace(1) %29, ptr %70, align 8
  %71 = getelementptr ptr, ptr %67, i32 1
  store ptr %70, ptr %71, align 8
  %72 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 2
  store i64 0, ptr %72, align 4
  %73 = getelementptr ptr, ptr %67, i32 2
  store ptr %72, ptr %73, align 8
  %74 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 3
  store i64 8, ptr %74, align 4
  %75 = getelementptr ptr, ptr %67, i32 3
  store ptr %74, ptr %75, align 8
  %76 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 4
  store i64 16, ptr %76, align 4
  %77 = getelementptr ptr, ptr %67, i32 4
  store ptr %76, ptr %77, align 8
  %78 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 5
  store i64 16, ptr %78, align 4
  %79 = getelementptr ptr, ptr %67, i32 5
  store ptr %78, ptr %79, align 8
  %80 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 6
  store i64 1, ptr %80, align 4
  %81 = getelementptr ptr, ptr %67, i32 6
  store ptr %80, ptr %81, align 8
  %82 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 7
  store ptr addrspace(1) %24, ptr %82, align 8
  %83 = getelementptr ptr, ptr %67, i32 7
  store ptr %82, ptr %83, align 8
  %84 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 8
  store ptr addrspace(1) %24, ptr %84, align 8
  %85 = getelementptr ptr, ptr %67, i32 8
  store ptr %84, ptr %85, align 8
  %86 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 9
  store i64 0, ptr %86, align 4
  %87 = getelementptr ptr, ptr %67, i32 9
  store ptr %86, ptr %87, align 8
  %88 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 10
  store i64 16, ptr %88, align 4
  %89 = getelementptr ptr, ptr %67, i32 10
  store ptr %88, ptr %89, align 8
  %90 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 11
  store i64 10, ptr %90, align 4
  %91 = getelementptr ptr, ptr %67, i32 11
  store ptr %90, ptr %91, align 8
  %92 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 12
  store i64 10, ptr %92, align 4
  %93 = getelementptr ptr, ptr %67, i32 12
  store ptr %92, ptr %93, align 8
  %94 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 13
  store i64 1, ptr %94, align 4
  %95 = getelementptr ptr, ptr %67, i32 13
  store ptr %94, ptr %95, align 8
  %96 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 14
  store ptr addrspace(1) %42, ptr %96, align 8
  %97 = getelementptr ptr, ptr %67, i32 14
  store ptr %96, ptr %97, align 8
  %98 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 15
  store ptr addrspace(1) %42, ptr %98, align 8
  %99 = getelementptr ptr, ptr %67, i32 15
  store ptr %98, ptr %99, align 8
  %100 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 16
  store i64 0, ptr %100, align 4
  %101 = getelementptr ptr, ptr %67, i32 16
  store ptr %100, ptr %101, align 8
  %102 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 17
  store i64 8, ptr %102, align 4
  %103 = getelementptr ptr, ptr %67, i32 17
  store ptr %102, ptr %103, align 8
  %104 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 18
  store i64 10, ptr %104, align 4
  %105 = getelementptr ptr, ptr %67, i32 18
  store ptr %104, ptr %105, align 8
  %106 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 19
  store i64 10, ptr %106, align 4
  %107 = getelementptr ptr, ptr %67, i32 19
  store ptr %106, ptr %107, align 8
  %108 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 20
  store i64 1, ptr %108, align 4
  %109 = getelementptr ptr, ptr %67, i32 20
  store ptr %108, ptr %109, align 8
  %110 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 21
  store i64 0, ptr %110, align 4
  %111 = getelementptr ptr, ptr %67, i32 21
  store ptr %110, ptr %111, align 8
  %112 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 22
  store i64 16, ptr %112, align 4
  %113 = getelementptr ptr, ptr %67, i32 22
  store ptr %112, ptr %113, align 8
  %114 = getelementptr inbounds nuw %1, ptr %66, i32 0, i32 23
  store i64 1, ptr %114, align 4
  %115 = getelementptr ptr, ptr %67, i32 23
  store ptr %114, ptr %115, align 8
  %116 = load ptr, ptr @main_kernel_0_module, align 8
  %117 = call ptr @mgpuModuleGetFunction(ptr %116, ptr @main_kernel_0_main_kernel_name)
  %118 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %117, i64 8, i64 10, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %118, ptr %67, ptr null, i64 24)
  call void @mgpuStreamSynchronize(ptr %118)
  call void @mgpuStreamDestroy(ptr %118)
  %119 = call i32 @cudaFree(ptr %25)
  %120 = call i32 @cudaFree(ptr %30)
  %121 = alloca ptr, align 8
  %122 = call i32 @cudaMalloc(ptr %121, i64 320)
  %123 = load ptr, ptr %121, align 8
  %124 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } undef, ptr %123, 0
  %125 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %124, ptr %123, 1
  %126 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %125, i64 0, 2
  %127 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %126, [2 x i64] [i64 8, i64 10], 3
  %128 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %127, [2 x i64] [i64 10, i64 1], 4
  %129 = alloca ptr addrspace(1), align 8
  %130 = call i32 @cudaMalloc(ptr %129, i64 320)
  %131 = load ptr addrspace(1), ptr %129, align 8
  %132 = addrspacecast ptr addrspace(1) %131 to ptr
  %133 = call i32 @cudaMemcpy(ptr %132, ptr %123, i64 320, i32 4)
  %134 = alloca %2, align 8
  %135 = alloca ptr, i64 20, align 8
  %136 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 0
  store ptr addrspace(1) %42, ptr %136, align 8
  %137 = getelementptr ptr, ptr %135, i32 0
  store ptr %136, ptr %137, align 8
  %138 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 1
  store ptr addrspace(1) %42, ptr %138, align 8
  %139 = getelementptr ptr, ptr %135, i32 1
  store ptr %138, ptr %139, align 8
  %140 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 2
  store i64 0, ptr %140, align 4
  %141 = getelementptr ptr, ptr %135, i32 2
  store ptr %140, ptr %141, align 8
  %142 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 3
  store i64 8, ptr %142, align 4
  %143 = getelementptr ptr, ptr %135, i32 3
  store ptr %142, ptr %143, align 8
  %144 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 4
  store i64 10, ptr %144, align 4
  %145 = getelementptr ptr, ptr %135, i32 4
  store ptr %144, ptr %145, align 8
  %146 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 5
  store i64 10, ptr %146, align 4
  %147 = getelementptr ptr, ptr %135, i32 5
  store ptr %146, ptr %147, align 8
  %148 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 6
  store i64 1, ptr %148, align 4
  %149 = getelementptr ptr, ptr %135, i32 6
  store ptr %148, ptr %149, align 8
  %150 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 7
  store ptr addrspace(1) %34, ptr %150, align 8
  %151 = getelementptr ptr, ptr %135, i32 7
  store ptr %150, ptr %151, align 8
  %152 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 8
  store ptr addrspace(1) %34, ptr %152, align 8
  %153 = getelementptr ptr, ptr %135, i32 8
  store ptr %152, ptr %153, align 8
  %154 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 9
  store i64 0, ptr %154, align 4
  %155 = getelementptr ptr, ptr %135, i32 9
  store ptr %154, ptr %155, align 8
  %156 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 10
  store i64 10, ptr %156, align 4
  %157 = getelementptr ptr, ptr %135, i32 10
  store ptr %156, ptr %157, align 8
  %158 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 11
  store i64 1, ptr %158, align 4
  %159 = getelementptr ptr, ptr %135, i32 11
  store ptr %158, ptr %159, align 8
  %160 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 12
  store float 0.000000e+00, ptr %160, align 4
  %161 = getelementptr ptr, ptr %135, i32 12
  store ptr %160, ptr %161, align 8
  %162 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 13
  store ptr addrspace(1) %131, ptr %162, align 8
  %163 = getelementptr ptr, ptr %135, i32 13
  store ptr %162, ptr %163, align 8
  %164 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 14
  store ptr addrspace(1) %131, ptr %164, align 8
  %165 = getelementptr ptr, ptr %135, i32 14
  store ptr %164, ptr %165, align 8
  %166 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 15
  store i64 0, ptr %166, align 4
  %167 = getelementptr ptr, ptr %135, i32 15
  store ptr %166, ptr %167, align 8
  %168 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 16
  store i64 8, ptr %168, align 4
  %169 = getelementptr ptr, ptr %135, i32 16
  store ptr %168, ptr %169, align 8
  %170 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 17
  store i64 10, ptr %170, align 4
  %171 = getelementptr ptr, ptr %135, i32 17
  store ptr %170, ptr %171, align 8
  %172 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 18
  store i64 10, ptr %172, align 4
  %173 = getelementptr ptr, ptr %135, i32 18
  store ptr %172, ptr %173, align 8
  %174 = getelementptr inbounds nuw %2, ptr %134, i32 0, i32 19
  store i64 1, ptr %174, align 4
  %175 = getelementptr ptr, ptr %135, i32 19
  store ptr %174, ptr %175, align 8
  %176 = load ptr, ptr @main_kernel_1_module, align 8
  %177 = call ptr @mgpuModuleGetFunction(ptr %176, ptr @main_kernel_1_main_kernel_name)
  %178 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %177, i64 8, i64 10, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %178, ptr %135, ptr null, i64 20)
  call void @mgpuStreamSynchronize(ptr %178)
  call void @mgpuStreamDestroy(ptr %178)
  %179 = call i32 @cudaFree(ptr %132)
  %180 = call i32 @cudaFree(ptr %43)
  %181 = call i32 @cudaFree(ptr %35)
  %182 = call i32 @cudaFree(ptr %39)
  ret { ptr, ptr, i64, [2 x i64], [2 x i64] } %128
}

define internal void @main_kernel_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main_kernel_binary, i32 2)
  store ptr %0, ptr @main_kernel_module, align 8
  ret void
}

declare ptr @mgpuModuleLoadJIT(ptr, i32)

define internal void @main_kernel_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main_kernel_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

declare void @mgpuModuleUnload(ptr)

define internal void @main_kernel_0_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main_kernel_0_binary, i32 2)
  store ptr %0, ptr @main_kernel_0_module, align 8
  ret void
}

define internal void @main_kernel_0_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main_kernel_0_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

define internal void @main_kernel_1_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main_kernel_1_binary, i32 2)
  store ptr %0, ptr @main_kernel_1_module, align 8
  ret void
}

define internal void @main_kernel_1_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main_kernel_1_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

declare ptr @mgpuModuleGetFunction(ptr, ptr)

declare ptr @mgpuStreamCreate()

declare void @mgpuLaunchKernel(ptr, i64, i64, i64, i64, i64, i64, i32, ptr, ptr, ptr, i64)

declare void @mgpuStreamSynchronize(ptr)

declare void @mgpuStreamDestroy(ptr)

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
