; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"

%0 = type { float, ptr addrspace(1), ptr addrspace(1), i64, i64, i64 }
%1 = type { ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, i64 }
%2 = type { ptr addrspace(1), ptr addrspace(1), i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64 }
%3 = type { ptr addrspace(1), ptr addrspace(1), i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64 }
%4 = type { ptr addrspace(1), ptr addrspace(1), i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64 }
%5 = type { ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64 }

@__constant_1xf32_0 = private constant [1 x float] [float 1.000000e+00], align 64
@__constant_1xf32 = private constant [1 x float] [float 1.250000e-01], align 64
@__constant_8x1xf32 = private constant [8 x [1 x float]] [[1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00], [1 x float] [float 1.000000e+00]], align 64
@__constant_8x16xf32 = private constant [8 x [16 x float]] [[16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00], [16 x float] [float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00]], align 64
@main1_kernel_binary = internal constant [667 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main1_kernel\0A\0A.visible .entry main1_kernel(\0A\09.param .f32 main1_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_1,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_2,\0A\09.param .u64 main1_kernel_param_3,\0A\09.param .u64 main1_kernel_param_4,\0A\09.param .u64 main1_kernel_param_5\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<3>;\0A\09.reg .b64 \09%rd<4>;\0A\0A\09ld.param.b32 \09%r1, [main1_kernel_param_0];\0A\09mov.u32 \09%r2, %ctaid.x;\0A\09ld.param.b64 \09%rd1, [main1_kernel_param_2];\0A\09mul.wide.u32 \09%rd2, %r2, 4;\0A\09add.s64 \09%rd3, %rd1, %rd2;\0A\09st.global.b32 \09[%rd3], %r1;\0A\09ret;\0A\0A}\0A\00", align 8
@main1_kernel_module = internal global ptr null
@main1_kernel_0_binary = internal constant [1621 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main1_kernel\0A\0A.visible .entry main1_kernel(\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_1,\0A\09.param .u64 main1_kernel_param_2,\0A\09.param .u64 main1_kernel_param_3,\0A\09.param .u64 main1_kernel_param_4,\0A\09.param .u64 main1_kernel_param_5,\0A\09.param .u64 main1_kernel_param_6,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_7,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_8,\0A\09.param .u64 main1_kernel_param_9,\0A\09.param .u64 main1_kernel_param_10,\0A\09.param .u64 main1_kernel_param_11,\0A\09.param .u64 main1_kernel_param_12,\0A\09.param .u64 main1_kernel_param_13,\0A\09.param .u64 main1_kernel_param_14\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .pred \09%p<3>;\0A\09.reg .b32 \09%r<7>;\0A\09.reg .b64 \09%rd<19>;\0A\0A\09ld.param.b64 \09%rd11, [main1_kernel_param_13];\0A\09ld.param.b64 \09%rd18, [main1_kernel_param_12];\0A\09setp.ge.s64 \09%p1, %rd18, %rd11;\0A\09@%p1 bra \09$L__BB0_3;\0A\09ld.param.b64 \09%rd12, [main1_kernel_param_14];\0A\09ld.param.b64 \09%rd9, [main1_kernel_param_8];\0A\09ld.param.b64 \09%rd8, [main1_kernel_param_1];\0A\09mov.u32 \09%r4, %ctaid.x;\0A\09mul.wide.u32 \09%rd13, %r4, 64;\0A\09mul.wide.u32 \09%rd14, %r4, 4;\0A\09add.s64 \09%rd1, %rd9, %rd14;\0A\09ld.global.b32 \09%r6, [%rd1];\0A\09shl.b64 \09%rd15, %rd18, 2;\0A\09add.s64 \09%rd16, %rd13, %rd15;\0A\09add.s64 \09%rd17, %rd8, %rd16;\0A\09shl.b64 \09%rd3, %rd12, 2;\0A$L__BB0_2:\0A\09ld.global.b32 \09%r5, [%rd17];\0A\09add.rn.f32 \09%r6, %r5, %r6;\0A\09st.global.b32 \09[%rd1], %r6;\0A\09add.s64 \09%rd18, %rd18, %rd12;\0A\09add.s64 \09%rd17, %rd17, %rd3;\0A\09setp.lt.s64 \09%p2, %rd18, %rd11;\0A\09@%p2 bra \09$L__BB0_2;\0A$L__BB0_3:\0A\09ret;\0A\0A}\0A\00", align 8
@main1_kernel_0_module = internal global ptr null
@main1_kernel_1_binary = internal constant [811 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main1_kernel\0A\0A.visible .entry main1_kernel(\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_1,\0A\09.param .u64 main1_kernel_param_2,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_3,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_4,\0A\09.param .u64 main1_kernel_param_5,\0A\09.param .u64 main1_kernel_param_6,\0A\09.param .u64 main1_kernel_param_7\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<3>;\0A\09.reg .b64 \09%rd<5>;\0A\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09ld.param.b64 \09%rd1, [main1_kernel_param_1];\0A\09ld.global.b32 \09%r2, [%rd1];\0A\09mul.wide.u32 \09%rd2, %r1, 4;\0A\09ld.param.b64 \09%rd3, [main1_kernel_param_4];\0A\09add.s64 \09%rd4, %rd3, %rd2;\0A\09st.global.b32 \09[%rd4], %r2;\0A\09ret;\0A\0A}\0A\00", align 8
@main1_kernel_1_module = internal global ptr null
@main1_kernel_2_binary = internal constant [1264 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main1_kernel\0A\0A.visible .entry main1_kernel(\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_1,\0A\09.param .u64 main1_kernel_param_2,\0A\09.param .u64 main1_kernel_param_3,\0A\09.param .u64 main1_kernel_param_4,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_5,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_6,\0A\09.param .u64 main1_kernel_param_7,\0A\09.param .u64 main1_kernel_param_8,\0A\09.param .u64 main1_kernel_param_9,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_10,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_11,\0A\09.param .u64 main1_kernel_param_12,\0A\09.param .u64 main1_kernel_param_13,\0A\09.param .u64 main1_kernel_param_14\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<5>;\0A\09.reg .b64 \09%rd<8>;\0A\0A\09ld.param.b64 \09%rd1, [main1_kernel_param_1];\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09mul.wide.u32 \09%rd2, %r1, 4;\0A\09add.s64 \09%rd3, %rd1, %rd2;\0A\09ld.global.b32 \09%r2, [%rd3];\0A\09ld.param.b64 \09%rd4, [main1_kernel_param_6];\0A\09add.s64 \09%rd5, %rd4, %rd2;\0A\09ld.global.b32 \09%r3, [%rd5];\0A\09mul.rn.f32 \09%r4, %r2, %r3;\0A\09ld.param.b64 \09%rd6, [main1_kernel_param_11];\0A\09add.s64 \09%rd7, %rd6, %rd2;\0A\09st.global.b32 \09[%rd7], %r4;\0A\09ret;\0A\0A}\0A\00", align 8
@main1_kernel_2_module = internal global ptr null
@main1_kernel_3_binary = internal constant [1093 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main1_kernel\0A\0A.visible .entry main1_kernel(\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_1,\0A\09.param .u64 main1_kernel_param_2,\0A\09.param .u64 main1_kernel_param_3,\0A\09.param .u64 main1_kernel_param_4,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_5,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_6,\0A\09.param .u64 main1_kernel_param_7,\0A\09.param .u64 main1_kernel_param_8,\0A\09.param .u64 main1_kernel_param_9,\0A\09.param .u64 main1_kernel_param_10,\0A\09.param .u64 main1_kernel_param_11\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<4>;\0A\09.reg .b64 \09%rd<9>;\0A\0A\09ld.param.b64 \09%rd1, [main1_kernel_param_1];\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09mov.u32 \09%r2, %ctaid.y;\0A\09mul.wide.u32 \09%rd2, %r1, 4;\0A\09add.s64 \09%rd3, %rd1, %rd2;\0A\09ld.global.b32 \09%r3, [%rd3];\0A\09ld.param.b64 \09%rd4, [main1_kernel_param_6];\0A\09mul.wide.u32 \09%rd5, %r1, 64;\0A\09add.s64 \09%rd6, %rd4, %rd5;\0A\09mul.wide.u32 \09%rd7, %r2, 4;\0A\09add.s64 \09%rd8, %rd6, %rd7;\0A\09st.global.b32 \09[%rd8], %r3;\0A\09ret;\0A\0A}\0A\00", align 8
@main1_kernel_3_module = internal global ptr null
@main1_kernel_4_binary = internal constant [1552 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.1\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main1_kernel\0A\0A.visible .entry main1_kernel(\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_0,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_1,\0A\09.param .u64 main1_kernel_param_2,\0A\09.param .u64 main1_kernel_param_3,\0A\09.param .u64 main1_kernel_param_4,\0A\09.param .u64 main1_kernel_param_5,\0A\09.param .u64 main1_kernel_param_6,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_7,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_8,\0A\09.param .u64 main1_kernel_param_9,\0A\09.param .u64 main1_kernel_param_10,\0A\09.param .u64 main1_kernel_param_11,\0A\09.param .u64 main1_kernel_param_12,\0A\09.param .u64 main1_kernel_param_13,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_14,\0A\09.param .u64 .ptr .global .align 1 main1_kernel_param_15,\0A\09.param .u64 main1_kernel_param_16,\0A\09.param .u64 main1_kernel_param_17,\0A\09.param .u64 main1_kernel_param_18,\0A\09.param .u64 main1_kernel_param_19,\0A\09.param .u64 main1_kernel_param_20\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.reg .b32 \09%r<8>;\0A\09.reg .b64 \09%rd<8>;\0A\0A\09ld.param.b64 \09%rd1, [main1_kernel_param_1];\0A\09mov.u32 \09%r1, %ctaid.x;\0A\09mov.u32 \09%r2, %ctaid.y;\0A\09shl.b32 \09%r3, %r1, 4;\0A\09or.b32 \09%r4, %r3, %r2;\0A\09mul.wide.u32 \09%rd2, %r4, 4;\0A\09add.s64 \09%rd3, %rd1, %rd2;\0A\09ld.global.b32 \09%r5, [%rd3];\0A\09ld.param.b64 \09%rd4, [main1_kernel_param_8];\0A\09add.s64 \09%rd5, %rd4, %rd2;\0A\09ld.global.b32 \09%r6, [%rd5];\0A\09mul.rn.f32 \09%r7, %r5, %r6;\0A\09ld.param.b64 \09%rd6, [main1_kernel_param_15];\0A\09add.s64 \09%rd7, %rd6, %rd2;\0A\09st.global.b32 \09[%rd7], %r7;\0A\09ret;\0A\0A}\0A\00", align 8
@main1_kernel_4_module = internal global ptr null
@llvm.global_ctors = appending global [6 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 123, ptr @main1_kernel_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_0_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_1_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_2_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_3_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_4_load, ptr null }]
@llvm.global_dtors = appending global [6 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 123, ptr @main1_kernel_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_0_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_1_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_2_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_3_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main1_kernel_4_unload, ptr null }]
@main1_kernel_main1_kernel_name = private unnamed_addr constant [13 x i8] c"main1_kernel\00", align 1
@main1_kernel_0_main1_kernel_name = private unnamed_addr constant [13 x i8] c"main1_kernel\00", align 1
@main1_kernel_1_main1_kernel_name = private unnamed_addr constant [13 x i8] c"main1_kernel\00", align 1
@main1_kernel_2_main1_kernel_name = private unnamed_addr constant [13 x i8] c"main1_kernel\00", align 1
@main1_kernel_3_main1_kernel_name = private unnamed_addr constant [13 x i8] c"main1_kernel\00", align 1
@main1_kernel_4_main1_kernel_name = private unnamed_addr constant [13 x i8] c"main1_kernel\00", align 1

declare i32 @cudaMalloc(ptr, i64)

declare i32 @cudaMemcpy(ptr, ptr, i64, i32)

declare i32 @cudaFree(ptr)

declare void @free(ptr)

declare ptr @malloc(i64)

define { { ptr, ptr, i64 }, { ptr, ptr, i64, [2 x i64], [2 x i64] } } @main1(ptr %0, ptr %1, i64 %2, i64 %3, i64 %4, i64 %5, i64 %6) {
  %8 = alloca ptr addrspace(1), align 8
  %9 = call i32 @cudaMalloc(ptr %8, i64 512)
  %10 = load ptr addrspace(1), ptr %8, align 8
  %11 = addrspacecast ptr addrspace(1) %10 to ptr
  %12 = call i32 @cudaMemcpy(ptr %11, ptr %1, i64 512, i32 4)
  %13 = alloca ptr addrspace(1), align 8
  %14 = call i32 @cudaMalloc(ptr %13, i64 512)
  %15 = load ptr addrspace(1), ptr %13, align 8
  %16 = addrspacecast ptr addrspace(1) %15 to ptr
  %17 = call i32 @cudaMemcpy(ptr %16, ptr @__constant_8x16xf32, i64 512, i32 4)
  %18 = call ptr @malloc(i64 96)
  %19 = ptrtoint ptr %18 to i64
  %20 = add i64 %19, 63
  %21 = urem i64 %20, 64
  %22 = sub i64 %20, %21
  %23 = inttoptr i64 %22 to ptr
  %24 = alloca ptr addrspace(1), align 8
  %25 = call i32 @cudaMalloc(ptr %24, i64 32)
  %26 = load ptr addrspace(1), ptr %24, align 8
  %27 = addrspacecast ptr addrspace(1) %26 to ptr
  %28 = call i32 @cudaMemcpy(ptr %27, ptr %23, i64 32, i32 4)
  %29 = alloca %0, align 8
  %30 = alloca ptr, i64 6, align 8
  %31 = getelementptr inbounds nuw %0, ptr %29, i32 0, i32 0
  store float 0.000000e+00, ptr %31, align 4
  %32 = getelementptr ptr, ptr %30, i32 0
  store ptr %31, ptr %32, align 8
  %33 = getelementptr inbounds nuw %0, ptr %29, i32 0, i32 1
  store ptr addrspace(1) %26, ptr %33, align 8
  %34 = getelementptr ptr, ptr %30, i32 1
  store ptr %33, ptr %34, align 8
  %35 = getelementptr inbounds nuw %0, ptr %29, i32 0, i32 2
  store ptr addrspace(1) %26, ptr %35, align 8
  %36 = getelementptr ptr, ptr %30, i32 2
  store ptr %35, ptr %36, align 8
  %37 = getelementptr inbounds nuw %0, ptr %29, i32 0, i32 3
  store i64 0, ptr %37, align 4
  %38 = getelementptr ptr, ptr %30, i32 3
  store ptr %37, ptr %38, align 8
  %39 = getelementptr inbounds nuw %0, ptr %29, i32 0, i32 4
  store i64 8, ptr %39, align 4
  %40 = getelementptr ptr, ptr %30, i32 4
  store ptr %39, ptr %40, align 8
  %41 = getelementptr inbounds nuw %0, ptr %29, i32 0, i32 5
  store i64 1, ptr %41, align 4
  %42 = getelementptr ptr, ptr %30, i32 5
  store ptr %41, ptr %42, align 8
  %43 = load ptr, ptr @main1_kernel_module, align 8
  %44 = call ptr @mgpuModuleGetFunction(ptr %43, ptr @main1_kernel_main1_kernel_name)
  %45 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %44, i64 8, i64 1, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %45, ptr %30, ptr null, i64 6)
  call void @mgpuStreamSynchronize(ptr %45)
  call void @mgpuStreamDestroy(ptr %45)
  %46 = alloca %1, align 8
  %47 = alloca ptr, i64 15, align 8
  %48 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 0
  store ptr addrspace(1) %10, ptr %48, align 8
  %49 = getelementptr ptr, ptr %47, i32 0
  store ptr %48, ptr %49, align 8
  %50 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 1
  store ptr addrspace(1) %10, ptr %50, align 8
  %51 = getelementptr ptr, ptr %47, i32 1
  store ptr %50, ptr %51, align 8
  %52 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 2
  store i64 0, ptr %52, align 4
  %53 = getelementptr ptr, ptr %47, i32 2
  store ptr %52, ptr %53, align 8
  %54 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 3
  store i64 8, ptr %54, align 4
  %55 = getelementptr ptr, ptr %47, i32 3
  store ptr %54, ptr %55, align 8
  %56 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 4
  store i64 16, ptr %56, align 4
  %57 = getelementptr ptr, ptr %47, i32 4
  store ptr %56, ptr %57, align 8
  %58 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 5
  store i64 16, ptr %58, align 4
  %59 = getelementptr ptr, ptr %47, i32 5
  store ptr %58, ptr %59, align 8
  %60 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 6
  store i64 1, ptr %60, align 4
  %61 = getelementptr ptr, ptr %47, i32 6
  store ptr %60, ptr %61, align 8
  %62 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 7
  store ptr addrspace(1) %26, ptr %62, align 8
  %63 = getelementptr ptr, ptr %47, i32 7
  store ptr %62, ptr %63, align 8
  %64 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 8
  store ptr addrspace(1) %26, ptr %64, align 8
  %65 = getelementptr ptr, ptr %47, i32 8
  store ptr %64, ptr %65, align 8
  %66 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 9
  store i64 0, ptr %66, align 4
  %67 = getelementptr ptr, ptr %47, i32 9
  store ptr %66, ptr %67, align 8
  %68 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 10
  store i64 8, ptr %68, align 4
  %69 = getelementptr ptr, ptr %47, i32 10
  store ptr %68, ptr %69, align 8
  %70 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 11
  store i64 1, ptr %70, align 4
  %71 = getelementptr ptr, ptr %47, i32 11
  store ptr %70, ptr %71, align 8
  %72 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 12
  store i64 0, ptr %72, align 4
  %73 = getelementptr ptr, ptr %47, i32 12
  store ptr %72, ptr %73, align 8
  %74 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 13
  store i64 16, ptr %74, align 4
  %75 = getelementptr ptr, ptr %47, i32 13
  store ptr %74, ptr %75, align 8
  %76 = getelementptr inbounds nuw %1, ptr %46, i32 0, i32 14
  store i64 1, ptr %76, align 4
  %77 = getelementptr ptr, ptr %47, i32 14
  store ptr %76, ptr %77, align 8
  %78 = load ptr, ptr @main1_kernel_0_module, align 8
  %79 = call ptr @mgpuModuleGetFunction(ptr %78, ptr @main1_kernel_0_main1_kernel_name)
  %80 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %79, i64 8, i64 1, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %80, ptr %47, ptr null, i64 15)
  call void @mgpuStreamSynchronize(ptr %80)
  call void @mgpuStreamDestroy(ptr %80)
  %81 = call i32 @cudaFree(ptr %11)
  %82 = call i32 @cudaFree(ptr %27)
  %83 = call ptr @malloc(i64 68)
  %84 = ptrtoint ptr %83 to i64
  %85 = add i64 %84, 63
  %86 = urem i64 %85, 64
  %87 = sub i64 %85, %86
  %88 = inttoptr i64 %87 to ptr
  store float 0.000000e+00, ptr %88, align 4
  br label %89

89:                                               ; preds = %92, %7
  %90 = phi i64 [ %97, %92 ], [ 0, %7 ]
  %91 = icmp slt i64 %90, 8
  br i1 %91, label %92, label %98

92:                                               ; preds = %89
  %93 = getelementptr inbounds nuw float, ptr %23, i64 %90
  %94 = load float, ptr %93, align 4
  %95 = load float, ptr %88, align 4
  %96 = fadd float %94, %95
  store float %96, ptr %88, align 4
  %97 = add i64 %90, 1
  br label %89

98:                                               ; preds = %89
  %99 = call ptr @malloc(i64 68)
  %100 = ptrtoint ptr %99 to i64
  %101 = add i64 %100, 63
  %102 = urem i64 %101, 64
  %103 = sub i64 %101, %102
  %104 = inttoptr i64 %103 to ptr
  %105 = insertvalue { ptr, ptr, i64 } poison, ptr %99, 0
  %106 = insertvalue { ptr, ptr, i64 } %105, ptr %104, 1
  %107 = insertvalue { ptr, ptr, i64 } %106, i64 0, 2
  %108 = load float, ptr %88, align 4
  %109 = fmul float %108, 1.250000e-01
  store float %109, ptr %104, align 4
  %110 = call ptr @malloc(i64 68)
  %111 = ptrtoint ptr %110 to i64
  %112 = add i64 %111, 63
  %113 = urem i64 %112, 64
  %114 = sub i64 %112, %113
  %115 = inttoptr i64 %114 to ptr
  %116 = alloca ptr addrspace(1), align 8
  %117 = call i32 @cudaMalloc(ptr %116, i64 4)
  %118 = load ptr addrspace(1), ptr %116, align 8
  %119 = addrspacecast ptr addrspace(1) %118 to ptr
  %120 = call i32 @cudaMemcpy(ptr %119, ptr %115, i64 4, i32 4)
  %121 = load float, ptr @__constant_1xf32_0, align 4
  %122 = load float, ptr @__constant_1xf32, align 4
  %123 = fmul float %121, %122
  store float %123, ptr %115, align 4
  %124 = call ptr @malloc(i64 96)
  %125 = ptrtoint ptr %124 to i64
  %126 = add i64 %125, 63
  %127 = urem i64 %126, 64
  %128 = sub i64 %126, %127
  %129 = inttoptr i64 %128 to ptr
  %130 = alloca ptr addrspace(1), align 8
  %131 = call i32 @cudaMalloc(ptr %130, i64 32)
  %132 = load ptr addrspace(1), ptr %130, align 8
  %133 = addrspacecast ptr addrspace(1) %132 to ptr
  %134 = call i32 @cudaMemcpy(ptr %133, ptr %129, i64 32, i32 4)
  %135 = alloca %2, align 8
  %136 = alloca ptr, i64 8, align 8
  %137 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 0
  store ptr addrspace(1) %118, ptr %137, align 8
  %138 = getelementptr ptr, ptr %136, i32 0
  store ptr %137, ptr %138, align 8
  %139 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 1
  store ptr addrspace(1) %118, ptr %139, align 8
  %140 = getelementptr ptr, ptr %136, i32 1
  store ptr %139, ptr %140, align 8
  %141 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 2
  store i64 0, ptr %141, align 4
  %142 = getelementptr ptr, ptr %136, i32 2
  store ptr %141, ptr %142, align 8
  %143 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 3
  store ptr addrspace(1) %132, ptr %143, align 8
  %144 = getelementptr ptr, ptr %136, i32 3
  store ptr %143, ptr %144, align 8
  %145 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 4
  store ptr addrspace(1) %132, ptr %145, align 8
  %146 = getelementptr ptr, ptr %136, i32 4
  store ptr %145, ptr %146, align 8
  %147 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 5
  store i64 0, ptr %147, align 4
  %148 = getelementptr ptr, ptr %136, i32 5
  store ptr %147, ptr %148, align 8
  %149 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 6
  store i64 8, ptr %149, align 4
  %150 = getelementptr ptr, ptr %136, i32 6
  store ptr %149, ptr %150, align 8
  %151 = getelementptr inbounds nuw %2, ptr %135, i32 0, i32 7
  store i64 1, ptr %151, align 4
  %152 = getelementptr ptr, ptr %136, i32 7
  store ptr %151, ptr %152, align 8
  %153 = load ptr, ptr @main1_kernel_1_module, align 8
  %154 = call ptr @mgpuModuleGetFunction(ptr %153, ptr @main1_kernel_1_main1_kernel_name)
  %155 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %154, i64 8, i64 1, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %155, ptr %136, ptr null, i64 8)
  call void @mgpuStreamSynchronize(ptr %155)
  call void @mgpuStreamDestroy(ptr %155)
  %156 = call i32 @cudaFree(ptr %119)
  %157 = call ptr @malloc(i64 96)
  %158 = ptrtoint ptr %157 to i64
  %159 = add i64 %158, 63
  %160 = urem i64 %159, 64
  %161 = sub i64 %159, %160
  %162 = inttoptr i64 %161 to ptr
  %163 = alloca ptr addrspace(1), align 8
  %164 = call i32 @cudaMalloc(ptr %163, i64 32)
  %165 = load ptr addrspace(1), ptr %163, align 8
  %166 = addrspacecast ptr addrspace(1) %165 to ptr
  %167 = call i32 @cudaMemcpy(ptr %166, ptr @__constant_8x1xf32, i64 32, i32 4)
  %168 = alloca ptr addrspace(1), align 8
  %169 = call i32 @cudaMalloc(ptr %168, i64 32)
  %170 = load ptr addrspace(1), ptr %168, align 8
  %171 = addrspacecast ptr addrspace(1) %170 to ptr
  %172 = call i32 @cudaMemcpy(ptr %171, ptr %162, i64 32, i32 4)
  %173 = alloca %3, align 8
  %174 = alloca ptr, i64 15, align 8
  %175 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 0
  store ptr addrspace(1) %132, ptr %175, align 8
  %176 = getelementptr ptr, ptr %174, i32 0
  store ptr %175, ptr %176, align 8
  %177 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 1
  store ptr addrspace(1) %132, ptr %177, align 8
  %178 = getelementptr ptr, ptr %174, i32 1
  store ptr %177, ptr %178, align 8
  %179 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 2
  store i64 0, ptr %179, align 4
  %180 = getelementptr ptr, ptr %174, i32 2
  store ptr %179, ptr %180, align 8
  %181 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 3
  store i64 8, ptr %181, align 4
  %182 = getelementptr ptr, ptr %174, i32 3
  store ptr %181, ptr %182, align 8
  %183 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 4
  store i64 1, ptr %183, align 4
  %184 = getelementptr ptr, ptr %174, i32 4
  store ptr %183, ptr %184, align 8
  %185 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 5
  store ptr addrspace(1) %165, ptr %185, align 8
  %186 = getelementptr ptr, ptr %174, i32 5
  store ptr %185, ptr %186, align 8
  %187 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 6
  store ptr addrspace(1) %165, ptr %187, align 8
  %188 = getelementptr ptr, ptr %174, i32 6
  store ptr %187, ptr %188, align 8
  %189 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 7
  store i64 0, ptr %189, align 4
  %190 = getelementptr ptr, ptr %174, i32 7
  store ptr %189, ptr %190, align 8
  %191 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 8
  store i64 8, ptr %191, align 4
  %192 = getelementptr ptr, ptr %174, i32 8
  store ptr %191, ptr %192, align 8
  %193 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 9
  store i64 1, ptr %193, align 4
  %194 = getelementptr ptr, ptr %174, i32 9
  store ptr %193, ptr %194, align 8
  %195 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 10
  store ptr addrspace(1) %170, ptr %195, align 8
  %196 = getelementptr ptr, ptr %174, i32 10
  store ptr %195, ptr %196, align 8
  %197 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 11
  store ptr addrspace(1) %170, ptr %197, align 8
  %198 = getelementptr ptr, ptr %174, i32 11
  store ptr %197, ptr %198, align 8
  %199 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 12
  store i64 0, ptr %199, align 4
  %200 = getelementptr ptr, ptr %174, i32 12
  store ptr %199, ptr %200, align 8
  %201 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 13
  store i64 8, ptr %201, align 4
  %202 = getelementptr ptr, ptr %174, i32 13
  store ptr %201, ptr %202, align 8
  %203 = getelementptr inbounds nuw %3, ptr %173, i32 0, i32 14
  store i64 1, ptr %203, align 4
  %204 = getelementptr ptr, ptr %174, i32 14
  store ptr %203, ptr %204, align 8
  %205 = load ptr, ptr @main1_kernel_2_module, align 8
  %206 = call ptr @mgpuModuleGetFunction(ptr %205, ptr @main1_kernel_2_main1_kernel_name)
  %207 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %206, i64 8, i64 1, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %207, ptr %174, ptr null, i64 15)
  call void @mgpuStreamSynchronize(ptr %207)
  call void @mgpuStreamDestroy(ptr %207)
  %208 = call i32 @cudaFree(ptr %166)
  %209 = call i32 @cudaFree(ptr %133)
  %210 = alloca ptr addrspace(1), align 8
  %211 = call i32 @cudaMalloc(ptr %210, i64 512)
  %212 = load ptr addrspace(1), ptr %210, align 8
  %213 = alloca %4, align 8
  %214 = alloca ptr, i64 12, align 8
  %215 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 0
  store ptr addrspace(1) %170, ptr %215, align 8
  %216 = getelementptr ptr, ptr %214, i32 0
  store ptr %215, ptr %216, align 8
  %217 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 1
  store ptr addrspace(1) %170, ptr %217, align 8
  %218 = getelementptr ptr, ptr %214, i32 1
  store ptr %217, ptr %218, align 8
  %219 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 2
  store i64 0, ptr %219, align 4
  %220 = getelementptr ptr, ptr %214, i32 2
  store ptr %219, ptr %220, align 8
  %221 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 3
  store i64 8, ptr %221, align 4
  %222 = getelementptr ptr, ptr %214, i32 3
  store ptr %221, ptr %222, align 8
  %223 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 4
  store i64 1, ptr %223, align 4
  %224 = getelementptr ptr, ptr %214, i32 4
  store ptr %223, ptr %224, align 8
  %225 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 5
  store ptr addrspace(1) %212, ptr %225, align 8
  %226 = getelementptr ptr, ptr %214, i32 5
  store ptr %225, ptr %226, align 8
  %227 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 6
  store ptr addrspace(1) %212, ptr %227, align 8
  %228 = getelementptr ptr, ptr %214, i32 6
  store ptr %227, ptr %228, align 8
  %229 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 7
  store i64 0, ptr %229, align 4
  %230 = getelementptr ptr, ptr %214, i32 7
  store ptr %229, ptr %230, align 8
  %231 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 8
  store i64 8, ptr %231, align 4
  %232 = getelementptr ptr, ptr %214, i32 8
  store ptr %231, ptr %232, align 8
  %233 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 9
  store i64 16, ptr %233, align 4
  %234 = getelementptr ptr, ptr %214, i32 9
  store ptr %233, ptr %234, align 8
  %235 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 10
  store i64 16, ptr %235, align 4
  %236 = getelementptr ptr, ptr %214, i32 10
  store ptr %235, ptr %236, align 8
  %237 = getelementptr inbounds nuw %4, ptr %213, i32 0, i32 11
  store i64 1, ptr %237, align 4
  %238 = getelementptr ptr, ptr %214, i32 11
  store ptr %237, ptr %238, align 8
  %239 = load ptr, ptr @main1_kernel_3_module, align 8
  %240 = call ptr @mgpuModuleGetFunction(ptr %239, ptr @main1_kernel_3_main1_kernel_name)
  %241 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %240, i64 8, i64 16, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %241, ptr %214, ptr null, i64 12)
  call void @mgpuStreamSynchronize(ptr %241)
  call void @mgpuStreamDestroy(ptr %241)
  %242 = call i32 @cudaFree(ptr %171)
  %243 = alloca ptr addrspace(1), align 8
  %244 = call i32 @cudaMalloc(ptr %243, i64 512)
  %245 = load ptr addrspace(1), ptr %243, align 8
  %246 = alloca %5, align 8
  %247 = alloca ptr, i64 21, align 8
  %248 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 0
  store ptr addrspace(1) %212, ptr %248, align 8
  %249 = getelementptr ptr, ptr %247, i32 0
  store ptr %248, ptr %249, align 8
  %250 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 1
  store ptr addrspace(1) %212, ptr %250, align 8
  %251 = getelementptr ptr, ptr %247, i32 1
  store ptr %250, ptr %251, align 8
  %252 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 2
  store i64 0, ptr %252, align 4
  %253 = getelementptr ptr, ptr %247, i32 2
  store ptr %252, ptr %253, align 8
  %254 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 3
  store i64 8, ptr %254, align 4
  %255 = getelementptr ptr, ptr %247, i32 3
  store ptr %254, ptr %255, align 8
  %256 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 4
  store i64 16, ptr %256, align 4
  %257 = getelementptr ptr, ptr %247, i32 4
  store ptr %256, ptr %257, align 8
  %258 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 5
  store i64 16, ptr %258, align 4
  %259 = getelementptr ptr, ptr %247, i32 5
  store ptr %258, ptr %259, align 8
  %260 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 6
  store i64 1, ptr %260, align 4
  %261 = getelementptr ptr, ptr %247, i32 6
  store ptr %260, ptr %261, align 8
  %262 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 7
  store ptr addrspace(1) %15, ptr %262, align 8
  %263 = getelementptr ptr, ptr %247, i32 7
  store ptr %262, ptr %263, align 8
  %264 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 8
  store ptr addrspace(1) %15, ptr %264, align 8
  %265 = getelementptr ptr, ptr %247, i32 8
  store ptr %264, ptr %265, align 8
  %266 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 9
  store i64 0, ptr %266, align 4
  %267 = getelementptr ptr, ptr %247, i32 9
  store ptr %266, ptr %267, align 8
  %268 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 10
  store i64 8, ptr %268, align 4
  %269 = getelementptr ptr, ptr %247, i32 10
  store ptr %268, ptr %269, align 8
  %270 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 11
  store i64 16, ptr %270, align 4
  %271 = getelementptr ptr, ptr %247, i32 11
  store ptr %270, ptr %271, align 8
  %272 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 12
  store i64 16, ptr %272, align 4
  %273 = getelementptr ptr, ptr %247, i32 12
  store ptr %272, ptr %273, align 8
  %274 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 13
  store i64 1, ptr %274, align 4
  %275 = getelementptr ptr, ptr %247, i32 13
  store ptr %274, ptr %275, align 8
  %276 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 14
  store ptr addrspace(1) %245, ptr %276, align 8
  %277 = getelementptr ptr, ptr %247, i32 14
  store ptr %276, ptr %277, align 8
  %278 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 15
  store ptr addrspace(1) %245, ptr %278, align 8
  %279 = getelementptr ptr, ptr %247, i32 15
  store ptr %278, ptr %279, align 8
  %280 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 16
  store i64 0, ptr %280, align 4
  %281 = getelementptr ptr, ptr %247, i32 16
  store ptr %280, ptr %281, align 8
  %282 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 17
  store i64 8, ptr %282, align 4
  %283 = getelementptr ptr, ptr %247, i32 17
  store ptr %282, ptr %283, align 8
  %284 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 18
  store i64 16, ptr %284, align 4
  %285 = getelementptr ptr, ptr %247, i32 18
  store ptr %284, ptr %285, align 8
  %286 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 19
  store i64 16, ptr %286, align 4
  %287 = getelementptr ptr, ptr %247, i32 19
  store ptr %286, ptr %287, align 8
  %288 = getelementptr inbounds nuw %5, ptr %246, i32 0, i32 20
  store i64 1, ptr %288, align 4
  %289 = getelementptr ptr, ptr %247, i32 20
  store ptr %288, ptr %289, align 8
  %290 = load ptr, ptr @main1_kernel_4_module, align 8
  %291 = call ptr @mgpuModuleGetFunction(ptr %290, ptr @main1_kernel_4_main1_kernel_name)
  %292 = call ptr @mgpuStreamCreate()
  call void @mgpuLaunchKernel(ptr %291, i64 8, i64 16, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %292, ptr %247, ptr null, i64 21)
  call void @mgpuStreamSynchronize(ptr %292)
  call void @mgpuStreamDestroy(ptr %292)
  %293 = call i32 @cudaFree(ptr %16)
  call void @free(ptr %18)
  call void @free(ptr %83)
  call void @free(ptr %110)
  call void @free(ptr %124)
  call void @free(ptr %157)
  %294 = addrspacecast ptr addrspace(1) %212 to ptr
  %295 = call i32 @cudaFree(ptr %294)
  %296 = call ptr @malloc(i64 512)
  %297 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } poison, ptr %296, 0
  %298 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %297, ptr %296, 1
  %299 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %298, i64 0, 2
  %300 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %299, i64 8, 3, 0
  %301 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %300, i64 16, 3, 1
  %302 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %301, i64 16, 4, 0
  %303 = insertvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %302, i64 1, 4, 1
  %304 = addrspacecast ptr addrspace(1) %245 to ptr
  %305 = call i32 @cudaMemcpy(ptr %296, ptr %304, i64 512, i32 4)
  %306 = call i32 @cudaFree(ptr %304)
  %307 = insertvalue { { ptr, ptr, i64 }, { ptr, ptr, i64, [2 x i64], [2 x i64] } } poison, { ptr, ptr, i64 } %107, 0
  %308 = insertvalue { { ptr, ptr, i64 }, { ptr, ptr, i64, [2 x i64], [2 x i64] } } %307, { ptr, ptr, i64, [2 x i64], [2 x i64] } %303, 1
  ret { { ptr, ptr, i64 }, { ptr, ptr, i64, [2 x i64], [2 x i64] } } %308
}

define void @_mlir_ciface_main1(ptr %0, ptr %1) {
  %3 = load { ptr, ptr, i64, [2 x i64], [2 x i64] }, ptr %1, align 8
  %4 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 0
  %5 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 1
  %6 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 2
  %7 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 3, 0
  %8 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 3, 1
  %9 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 4, 0
  %10 = extractvalue { ptr, ptr, i64, [2 x i64], [2 x i64] } %3, 4, 1
  %11 = call { { ptr, ptr, i64 }, { ptr, ptr, i64, [2 x i64], [2 x i64] } } @main1(ptr %4, ptr %5, i64 %6, i64 %7, i64 %8, i64 %9, i64 %10)
  store { { ptr, ptr, i64 }, { ptr, ptr, i64, [2 x i64], [2 x i64] } } %11, ptr %0, align 8
  ret void
}

define internal void @main1_kernel_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main1_kernel_binary, i32 2)
  store ptr %0, ptr @main1_kernel_module, align 8
  ret void
}

declare ptr @mgpuModuleLoadJIT(ptr, i32)

define internal void @main1_kernel_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main1_kernel_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

declare void @mgpuModuleUnload(ptr)

define internal void @main1_kernel_0_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main1_kernel_0_binary, i32 2)
  store ptr %0, ptr @main1_kernel_0_module, align 8
  ret void
}

define internal void @main1_kernel_0_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main1_kernel_0_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

define internal void @main1_kernel_1_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main1_kernel_1_binary, i32 2)
  store ptr %0, ptr @main1_kernel_1_module, align 8
  ret void
}

define internal void @main1_kernel_1_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main1_kernel_1_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

define internal void @main1_kernel_2_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main1_kernel_2_binary, i32 2)
  store ptr %0, ptr @main1_kernel_2_module, align 8
  ret void
}

define internal void @main1_kernel_2_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main1_kernel_2_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

define internal void @main1_kernel_3_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main1_kernel_3_binary, i32 2)
  store ptr %0, ptr @main1_kernel_3_module, align 8
  ret void
}

define internal void @main1_kernel_3_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main1_kernel_3_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

define internal void @main1_kernel_4_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main1_kernel_4_binary, i32 2)
  store ptr %0, ptr @main1_kernel_4_module, align 8
  ret void
}

define internal void @main1_kernel_4_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main1_kernel_4_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

declare ptr @mgpuModuleGetFunction(ptr, ptr)

declare ptr @mgpuStreamCreate()

declare void @mgpuLaunchKernel(ptr, i64, i64, i64, i64, i64, i64, i32, ptr, ptr, ptr, i64)

declare void @mgpuStreamSynchronize(ptr)

declare void @mgpuStreamDestroy(ptr)

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
