; ModuleID = 'LLVMDialectModule'
source_filename = "LLVMDialectModule"

%0 = type { i64, ptr, ptr, i64, i64, i64, i64, i64, float, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, i64, i64, i64, i64, float }
%1 = type { i64, float, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, i64, i64, i64, i64, float, ptr, ptr, i64, i64, i64, i64, i64, ptr addrspace(1), ptr addrspace(1), i64, i64, i64, i64, i64, float, ptr, ptr, i64 }

@main_kernel_binary = internal constant [6616 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.6\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main_kernel\0A\0A.visible .entry main_kernel(\0A\09.param .u64 main_kernel_param_0,\0A\09.param .u64 .ptr .align 1 main_kernel_param_1,\0A\09.param .u64 .ptr .align 1 main_kernel_param_2,\0A\09.param .u64 main_kernel_param_3,\0A\09.param .u64 main_kernel_param_4,\0A\09.param .u64 main_kernel_param_5,\0A\09.param .u64 main_kernel_param_6,\0A\09.param .u64 main_kernel_param_7,\0A\09.param .f32 main_kernel_param_8,\0A\09.param .u64 main_kernel_param_9,\0A\09.param .u64 main_kernel_param_10,\0A\09.param .u64 main_kernel_param_11,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_12,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_13,\0A\09.param .u64 main_kernel_param_14,\0A\09.param .u64 main_kernel_param_15,\0A\09.param .u64 main_kernel_param_16,\0A\09.param .u64 main_kernel_param_17,\0A\09.param .u64 main_kernel_param_18,\0A\09.param .u64 main_kernel_param_19,\0A\09.param .u64 main_kernel_param_20,\0A\09.param .u64 main_kernel_param_21,\0A\09.param .u64 main_kernel_param_22,\0A\09.param .f32 main_kernel_param_23\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.local .align 4 .b8 \09__local_depot0[4096];\0A\09.reg .b64 \09%SP;\0A\09.reg .b64 \09%SPL;\0A\09.reg .pred \09%p<29>;\0A\09.reg .b32 \09%r<32>;\0A\09.reg .b64 \09%rd<130>;\0A\0A\09mov.b64 \09%SPL, __local_depot0;\0A\09ld.param.b64 \09%rd80, [main_kernel_param_22];\0A\09ld.param.b64 \09%rd79, [main_kernel_param_21];\0A\09ld.param.b64 \09%rd77, [main_kernel_param_11];\0A\09ld.param.b64 \09%rd76, [main_kernel_param_10];\0A\09ld.param.b64 \09%rd75, [main_kernel_param_9];\0A\09ld.param.b64 \09%rd74, [main_kernel_param_0];\0A\09ld.param.b64 \09%rd81, [main_kernel_param_2];\0A\09cvta.to.global.u64 \09%rd1, %rd81;\0A\09mov.u32 \09%r12, %ctaid.x;\0A\09cvt.u64.u32 \09%rd82, %r12;\0A\09add.u64 \09%rd3, %SPL, 0;\0A\09setp.ge.s64 \09%p1, %rd75, %rd77;\0A\09shl.b64 \09%rd105, %rd76, 2;\0A\09setp.ge.s64 \09%p28, %rd75, %rd74;\0A\09@%p1 bra \09$L__BB0_5;\0A\09ld.param.b32 \09%r10, [main_kernel_param_8];\0A\09mad.lo.s64 \09%rd106, %rd75, 516, %rd3;\0A\09shl.b64 \09%rd5, %rd76, 9;\0A\09mov.b64 \09%rd107, %rd75;\0A\09bra.uni \09$L__BB0_2;\0A$L__BB0_4:\0A\09add.s64 \09%rd107, %rd107, %rd76;\0A\09add.s64 \09%rd106, %rd106, %rd5;\0A\09setp.lt.s64 \09%p4, %rd107, %rd77;\0A\09@%p4 bra \09$L__BB0_2;\0A\09bra.uni \09$L__BB0_5;\0A$L__BB0_2:\0A\09mov.b64 \09%rd108, %rd106;\0A\09mov.b64 \09%rd109, %rd75;\0A\09@%p28 bra \09$L__BB0_4;\0A$L__BB0_3:\0A\09st.local.b32 \09[%rd108], %r10;\0A\09add.s64 \09%rd109, %rd109, %rd76;\0A\09add.s64 \09%rd108, %rd108, %rd105;\0A\09setp.lt.s64 \09%p3, %rd109, %rd74;\0A\09@%p3 bra \09$L__BB0_3;\0A\09bra.uni \09$L__BB0_4;\0A$L__BB0_5:\0A\09ld.param.b64 \09%rd78, [main_kernel_param_13];\0A\09mul.lo.s64 \09%rd2, %rd74, %rd82;\0A\09setp.ge.s64 \09%p5, %rd75, %rd80;\0A\09mul.lo.s64 \09%rd100, %rd75, 6297608;\0A\09shl.b64 \09%rd101, %rd79, 2;\0A\09mul.lo.s64 \09%rd102, %rd76, 6291456;\0A\09mul.lo.s64 \09%rd103, %rd76, 6144;\0A\09setp.ge.s64 \09%p27, %rd75, %rd79;\0A\09@%p5 bra \09$L__BB0_16;\0A\09mad.lo.s64 \09%rd85, %rd2, 6144, %rd100;\0A\09add.s64 \09%rd110, %rd78, %rd85;\0A\09mov.b64 \09%rd111, %rd75;\0A\09bra.uni \09$L__BB0_7;\0A$L__BB0_15:\0A\09add.s64 \09%rd111, %rd111, %rd79;\0A\09add.s64 \09%rd110, %rd110, %rd101;\0A\09setp.lt.s64 \09%p12, %rd111, %rd80;\0A\09@%p12 bra \09$L__BB0_7;\0A\09bra.uni \09$L__BB0_16;\0A$L__BB0_7:\0A\09mov.b64 \09%rd112, %rd110;\0A\09mov.b64 \09%rd113, %rd75;\0A\09@%p1 bra \09$L__BB0_15;\0A\09bra.uni \09$L__BB0_8;\0A$L__BB0_14:\0A\09add.s64 \09%rd113, %rd113, %rd76;\0A\09add.s64 \09%rd112, %rd112, %rd102;\0A\09setp.lt.s64 \09%p11, %rd113, %rd77;\0A\09@%p11 bra \09$L__BB0_8;\0A\09bra.uni \09$L__BB0_15;\0A$L__BB0_8:\0A\09@%p28 bra \09$L__BB0_14;\0A\09shl.b64 \09%rd86, %rd113, 9;\0A\09add.s64 \09%rd27, %rd3, %rd86;\0A\09mov.b64 \09%rd114, %rd112;\0A\09mov.b64 \09%rd115, %rd75;\0A\09bra.uni \09$L__BB0_10;\0A$L__BB0_13:\0A\09st.local.b32 \09[%rd30], %r29;\0A\09add.s64 \09%rd115, %rd115, %rd76;\0A\09add.s64 \09%rd114, %rd114, %rd103;\0A\09setp.lt.s64 \09%p10, %rd115, %rd74;\0A\09@%p10 bra \09$L__BB0_10;\0A\09bra.uni \09$L__BB0_14;\0A$L__BB0_10:\0A\09shl.b64 \09%rd87, %rd115, 2;\0A\09add.s64 \09%rd30, %rd27, %rd87;\0A\09ld.local.b32 \09%r29, [%rd30];\0A\09@%p27 bra \09$L__BB0_13;\0A\09mov.b64 \09%rd116, %rd114;\0A\09mov.b64 \09%rd117, %rd75;\0A$L__BB0_12:\0A\09ld.global.b32 \09%r13, [%rd116];\0A\09max.NaN.f32 \09%r29, %r13, %r29;\0A\09add.s64 \09%rd117, %rd117, %rd76;\0A\09add.s64 \09%rd116, %rd116, %rd105;\0A\09setp.lt.s64 \09%p9, %rd117, %rd79;\0A\09@%p9 bra \09$L__BB0_12;\0A\09bra.uni \09$L__BB0_13;\0A$L__BB0_16:\0A\09shl.b64 \09%rd98, %rd2, 2;\0A\09@%p1 bra \09$L__BB0_21;\0A\09ld.param.b32 \09%r11, [main_kernel_param_23];\0A\09mad.lo.s64 \09%rd89, %rd75, 4100, %rd98;\0A\09add.s64 \09%rd118, %rd1, %rd89;\0A\09shl.b64 \09%rd23, %rd76, 12;\0A\09mov.b64 \09%rd119, %rd75;\0A\09bra.uni \09$L__BB0_18;\0A$L__BB0_20:\0A\09add.s64 \09%rd119, %rd119, %rd76;\0A\09add.s64 \09%rd118, %rd118, %rd23;\0A\09setp.lt.s64 \09%p16, %rd119, %rd77;\0A\09@%p16 bra \09$L__BB0_18;\0A\09bra.uni \09$L__BB0_21;\0A$L__BB0_18:\0A\09mov.b64 \09%rd120, %rd118;\0A\09mov.b64 \09%rd121, %rd75;\0A\09@%p28 bra \09$L__BB0_20;\0A$L__BB0_19:\0A\09st.global.b32 \09[%rd120], %r11;\0A\09add.s64 \09%rd121, %rd121, %rd76;\0A\09add.s64 \09%rd120, %rd120, %rd105;\0A\09setp.lt.s64 \09%p15, %rd121, %rd74;\0A\09@%p15 bra \09$L__BB0_19;\0A\09bra.uni \09$L__BB0_20;\0A$L__BB0_21:\0A\09@%p5 bra \09$L__BB0_33;\0A\09add.s64 \09%rd43, %rd1, %rd98;\0A\09mad.lo.s64 \09%rd92, %rd2, 6144, %rd100;\0A\09add.s64 \09%rd122, %rd78, %rd92;\0A\09mov.b64 \09%rd123, %rd75;\0A\09bra.uni \09$L__BB0_23;\0A$L__BB0_32:\0A\09add.s64 \09%rd123, %rd123, %rd79;\0A\09add.s64 \09%rd122, %rd122, %rd101;\0A\09setp.lt.s64 \09%p24, %rd123, %rd80;\0A\09@%p24 bra \09$L__BB0_23;\0A\09bra.uni \09$L__BB0_33;\0A$L__BB0_23:\0A\09@%p1 bra \09$L__BB0_32;\0A\09mov.b64 \09%rd124, %rd122;\0A\09mov.b64 \09%rd125, %rd75;\0A\09bra.uni \09$L__BB0_25;\0A$L__BB0_31:\0A\09add.s64 \09%rd125, %rd125, %rd76;\0A\09add.s64 \09%rd124, %rd124, %rd102;\0A\09setp.lt.s64 \09%p23, %rd125, %rd77;\0A\09@%p23 bra \09$L__BB0_25;\0A\09bra.uni \09$L__BB0_32;\0A$L__BB0_25:\0A\09@%p28 bra \09$L__BB0_31;\0A\09shl.b64 \09%rd93, %rd125, 12;\0A\09add.s64 \09%rd59, %rd43, %rd93;\0A\09shl.b64 \09%rd94, %rd125, 9;\0A\09add.s64 \09%rd60, %rd3, %rd94;\0A\09mov.b64 \09%rd126, %rd124;\0A\09mov.b64 \09%rd127, %rd75;\0A\09bra.uni \09$L__BB0_27;\0A$L__BB0_30:\0A\09st.global.b32 \09[%rd63], %r31;\0A\09add.s64 \09%rd127, %rd127, %rd76;\0A\09add.s64 \09%rd126, %rd126, %rd103;\0A\09setp.lt.s64 \09%p22, %rd127, %rd74;\0A\09@%p22 bra \09$L__BB0_27;\0A\09bra.uni \09$L__BB0_31;\0A$L__BB0_27:\0A\09shl.b64 \09%rd95, %rd127, 2;\0A\09add.s64 \09%rd63, %rd59, %rd95;\0A\09ld.global.b32 \09%r31, [%rd63];\0A\09@%p27 bra \09$L__BB0_30;\0A\09add.s64 \09%rd97, %rd60, %rd95;\0A\09ld.local.b32 \09%r6, [%rd97];\0A\09mov.b64 \09%rd128, %rd126;\0A\09mov.b64 \09%rd129, %rd75;\0A$L__BB0_29:\0A\09ld.global.b32 \09%r14, [%rd128];\0A\09sub.rn.f32 \09%r15, %r14, %r6;\0A\09fma.rn.f32 \09%r16, %r15, 0f3BBB989D, 0f3F000000;\0A\09cvt.sat.f32.f32 \09%r17, %r16;\0A\09mov.b32 \09%r18, 0f4B400001;\0A\09mov.b32 \09%r19, 0f437C0000;\0A\09fma.rm.f32 \09%r20, %r17, %r19, %r18;\0A\09add.rn.f32 \09%r21, %r20, 0fCB40007F;\0A\09neg.f32 \09%r22, %r21;\0A\09fma.rn.f32 \09%r23, %r15, 0f3FB8AA3B, %r22;\0A\09fma.rn.f32 \09%r24, %r15, 0f32A57060, %r23;\0A\09shl.b32 \09%r25, %r20, 23;\0A\09ex2.approx.ftz.f32 \09%r26, %r24;\0A\09mul.rn.f32 \09%r27, %r26, %r25;\0A\09add.rn.f32 \09%r31, %r31, %r27;\0A\09add.s64 \09%rd129, %rd129, %rd76;\0A\09add.s64 \09%rd128, %rd128, %rd105;\0A\09setp.lt.s64 \09%p21, %rd129, %rd79;\0A\09@%p21 bra \09$L__BB0_29;\0A\09bra.uni \09$L__BB0_30;\0A$L__BB0_33:\0A\09ret;\0A\0A}\0A\00", align 8
@main_kernel_module = internal global ptr null
@main_kernel_0_binary = internal constant [8055 x i8] c"//\0A// Generated by LLVM NVPTX Back-End\0A//\0A\0A.version 7.6\0A.target sm_86\0A.address_size 64\0A\0A\09// .globl\09main_kernel\0A\0A.visible .entry main_kernel(\0A\09.param .u64 main_kernel_param_0,\0A\09.param .f32 main_kernel_param_1,\0A\09.param .u64 main_kernel_param_2,\0A\09.param .u64 main_kernel_param_3,\0A\09.param .u64 main_kernel_param_4,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_5,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_6,\0A\09.param .u64 main_kernel_param_7,\0A\09.param .u64 main_kernel_param_8,\0A\09.param .u64 main_kernel_param_9,\0A\09.param .u64 main_kernel_param_10,\0A\09.param .u64 main_kernel_param_11,\0A\09.param .u64 main_kernel_param_12,\0A\09.param .u64 main_kernel_param_13,\0A\09.param .u64 main_kernel_param_14,\0A\09.param .u64 main_kernel_param_15,\0A\09.param .f32 main_kernel_param_16,\0A\09.param .u64 .ptr .align 1 main_kernel_param_17,\0A\09.param .u64 .ptr .align 1 main_kernel_param_18,\0A\09.param .u64 main_kernel_param_19,\0A\09.param .u64 main_kernel_param_20,\0A\09.param .u64 main_kernel_param_21,\0A\09.param .u64 main_kernel_param_22,\0A\09.param .u64 main_kernel_param_23,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_24,\0A\09.param .u64 .ptr .global .align 1 main_kernel_param_25,\0A\09.param .u64 main_kernel_param_26,\0A\09.param .u64 main_kernel_param_27,\0A\09.param .u64 main_kernel_param_28,\0A\09.param .u64 main_kernel_param_29,\0A\09.param .u64 main_kernel_param_30,\0A\09.param .f32 main_kernel_param_31,\0A\09.param .u64 .ptr .align 1 main_kernel_param_32,\0A\09.param .u64 .ptr .align 1 main_kernel_param_33,\0A\09.param .u64 main_kernel_param_34\0A)\0A.maxntid 1, 1, 1\0A{\0A\09.local .align 4 .b8 \09__local_depot0[4096];\0A\09.reg .b64 \09%SP;\0A\09.reg .b64 \09%SPL;\0A\09.reg .pred \09%p<26>;\0A\09.reg .b32 \09%r<58>;\0A\09.reg .b64 \09%rd<151>;\0A\0A\09mov.b64 \09%SPL, __local_depot0;\0A\09ld.param.b64 \09%rd95, [main_kernel_param_15];\0A\09ld.param.b64 \09%rd94, [main_kernel_param_14];\0A\09ld.param.b64 \09%rd92, [main_kernel_param_4];\0A\09ld.param.b64 \09%rd91, [main_kernel_param_3];\0A\09ld.param.b64 \09%rd90, [main_kernel_param_2];\0A\09ld.param.b64 \09%rd89, [main_kernel_param_0];\0A\09ld.param.b64 \09%rd97, [main_kernel_param_18];\0A\09cvta.to.global.u64 \09%rd1, %rd97;\0A\09ld.param.b64 \09%rd98, [main_kernel_param_33];\0A\09cvta.to.global.u64 \09%rd2, %rd98;\0A\09mov.u32 \09%r16, %ctaid.x;\0A\09cvt.u64.u32 \09%rd99, %r16;\0A\09add.u64 \09%rd4, %SPL, 0;\0A\09setp.ge.s64 \09%p1, %rd90, %rd92;\0A\09shl.b64 \09%rd119, %rd91, 9;\0A\09shl.b64 \09%rd120, %rd91, 2;\0A\09setp.ge.s64 \09%p25, %rd90, %rd89;\0A\09@%p1 bra \09$L__BB0_5;\0A\09ld.param.b32 \09%r13, [main_kernel_param_1];\0A\09mad.lo.s64 \09%rd121, %rd90, 516, %rd4;\0A\09mov.b64 \09%rd122, %rd90;\0A\09bra.uni \09$L__BB0_2;\0A$L__BB0_4:\0A\09add.s64 \09%rd122, %rd122, %rd91;\0A\09add.s64 \09%rd121, %rd121, %rd119;\0A\09setp.lt.s64 \09%p4, %rd122, %rd92;\0A\09@%p4 bra \09$L__BB0_2;\0A\09bra.uni \09$L__BB0_5;\0A$L__BB0_2:\0A\09mov.b64 \09%rd123, %rd121;\0A\09mov.b64 \09%rd124, %rd90;\0A\09@%p25 bra \09$L__BB0_4;\0A$L__BB0_3:\0A\09st.local.b32 \09[%rd123], %r13;\0A\09add.s64 \09%rd124, %rd124, %rd91;\0A\09add.s64 \09%rd123, %rd123, %rd120;\0A\09setp.lt.s64 \09%p3, %rd124, %rd89;\0A\09@%p3 bra \09$L__BB0_3;\0A\09bra.uni \09$L__BB0_4;\0A$L__BB0_5:\0A\09ld.param.b64 \09%rd93, [main_kernel_param_6];\0A\09mul.lo.s64 \09%rd3, %rd89, %rd99;\0A\09setp.ge.s64 \09%p5, %rd90, %rd95;\0A\09shl.b64 \09%rd115, %rd94, 2;\0A\09mul.lo.s64 \09%rd116, %rd91, 6291456;\0A\09mul.lo.s64 \09%rd117, %rd91, 6144;\0A\09setp.ge.s64 \09%p24, %rd90, %rd94;\0A\09@%p5 bra \09$L__BB0_17;\0A\09mul.lo.s64 \09%rd101, %rd90, 6297608;\0A\09mad.lo.s64 \09%rd102, %rd3, 6144, %rd101;\0A\09add.s64 \09%rd125, %rd93, %rd102;\0A\09mov.b64 \09%rd126, %rd90;\0A\09bra.uni \09$L__BB0_7;\0A$L__BB0_16:\0A\09add.s64 \09%rd126, %rd126, %rd94;\0A\09add.s64 \09%rd125, %rd125, %rd115;\0A\09setp.lt.s64 \09%p12, %rd126, %rd95;\0A\09@%p12 bra \09$L__BB0_7;\0A\09bra.uni \09$L__BB0_17;\0A$L__BB0_7:\0A\09@%p1 bra \09$L__BB0_16;\0A\09mov.b64 \09%rd127, %rd125;\0A\09mov.b64 \09%rd128, %rd90;\0A\09bra.uni \09$L__BB0_9;\0A$L__BB0_15:\0A\09add.s64 \09%rd128, %rd128, %rd91;\0A\09add.s64 \09%rd127, %rd127, %rd116;\0A\09setp.lt.s64 \09%p11, %rd128, %rd92;\0A\09@%p11 bra \09$L__BB0_9;\0A\09bra.uni \09$L__BB0_16;\0A$L__BB0_9:\0A\09@%p25 bra \09$L__BB0_15;\0A\09shl.b64 \09%rd103, %rd128, 9;\0A\09add.s64 \09%rd25, %rd4, %rd103;\0A\09mov.b64 \09%rd129, %rd127;\0A\09mov.b64 \09%rd130, %rd90;\0A\09bra.uni \09$L__BB0_11;\0A$L__BB0_14:\0A\09st.local.b32 \09[%rd28], %r50;\0A\09add.s64 \09%rd130, %rd130, %rd91;\0A\09add.s64 \09%rd129, %rd129, %rd117;\0A\09setp.lt.s64 \09%p10, %rd130, %rd89;\0A\09@%p10 bra \09$L__BB0_11;\0A\09bra.uni \09$L__BB0_15;\0A$L__BB0_11:\0A\09shl.b64 \09%rd104, %rd130, 2;\0A\09add.s64 \09%rd28, %rd25, %rd104;\0A\09ld.local.b32 \09%r50, [%rd28];\0A\09@%p24 bra \09$L__BB0_14;\0A\09mov.b64 \09%rd131, %rd129;\0A\09mov.b64 \09%rd132, %rd90;\0A$L__BB0_13:\0A\09ld.global.b32 \09%r17, [%rd131];\0A\09max.f32 \09%r50, %r17, %r50;\0A\09add.s64 \09%rd132, %rd132, %rd91;\0A\09add.s64 \09%rd131, %rd131, %rd120;\0A\09setp.lt.s64 \09%p9, %rd132, %rd94;\0A\09@%p9 bra \09$L__BB0_13;\0A\09bra.uni \09$L__BB0_14;\0A$L__BB0_17:\0A\09ld.param.b32 \09%r15, [main_kernel_param_31];\0A\09ld.param.b32 \09%r54, [main_kernel_param_16];\0A\09@%p1 bra \09$L__BB0_28;\0A\09ld.param.b64 \09%rd96, [main_kernel_param_25];\0A\09mad.lo.s64 \09%rd136, %rd90, 1032, %rd4;\0A\09shl.b64 \09%rd40, %rd94, 9;\0A\09shl.b64 \09%rd105, %rd3, 2;\0A\09mad.lo.s64 \09%rd106, %rd90, 8200, %rd105;\0A\09add.s64 \09%rd135, %rd1, %rd106;\0A\09shl.b64 \09%rd45, %rd94, 12;\0A\09shl.b64 \09%rd46, %rd91, 12;\0A\09add.s64 \09%rd134, %rd96, %rd106;\0A\09mul.lo.s64 \09%rd107, %rd90, 12595200;\0A\09mad.lo.s64 \09%rd108, %rd3, 6144, %rd107;\0A\09add.s64 \09%rd133, %rd93, %rd108;\0A\09mul.lo.s64 \09%rd49, %rd94, 6291456;\0A\09mul.lo.s64 \09%rd50, %rd94, 6144;\0A\09mov.b64 \09%rd137, %rd90;\0A\09bra.uni \09$L__BB0_19;\0A$L__BB0_27:\0A\09add.s64 \09%rd137, %rd137, %rd94;\0A\09add.s64 \09%rd136, %rd136, %rd40;\0A\09add.s64 \09%rd135, %rd135, %rd45;\0A\09add.s64 \09%rd134, %rd134, %rd45;\0A\09add.s64 \09%rd133, %rd133, %rd49;\0A\09setp.lt.s64 \09%p22, %rd137, %rd92;\0A\09@%p22 bra \09$L__BB0_19;\0A\09bra.uni \09$L__BB0_28;\0A$L__BB0_19:\0A\09@%p25 bra \09$L__BB0_27;\0A\09mov.b64 \09%rd138, %rd133;\0A\09mov.b64 \09%rd139, %rd134;\0A\09mov.b64 \09%rd140, %rd135;\0A\09mov.b64 \09%rd141, %rd136;\0A\09mov.b64 \09%rd142, %rd90;\0A\09bra.uni \09$L__BB0_21;\0A$L__BB0_26:\0A\09add.s64 \09%rd142, %rd142, %rd94;\0A\09add.s64 \09%rd141, %rd141, %rd115;\0A\09add.s64 \09%rd140, %rd140, %rd115;\0A\09add.s64 \09%rd139, %rd139, %rd115;\0A\09add.s64 \09%rd138, %rd138, %rd50;\0A\09setp.lt.s64 \09%p21, %rd142, %rd89;\0A\09@%p21 bra \09$L__BB0_21;\0A\09bra.uni \09$L__BB0_27;\0A$L__BB0_21:\0A\09@%p24 bra \09$L__BB0_26;\0A\09mov.b64 \09%rd143, %rd138;\0A\09mov.b64 \09%rd144, %rd139;\0A\09mov.b64 \09%rd145, %rd140;\0A\09mov.b64 \09%rd146, %rd141;\0A\09mov.b64 \09%rd147, %rd90;\0A$L__BB0_23:\0A\09mov.b64 \09%rd149, 0;\0A\09mov.b64 \09%rd148, %rd143;\0A\09mov.b64 \09%rd150, %rd90;\0A$L__BB0_24:\0A\09add.s64 \09%rd110, %rd145, %rd149;\0A\09ld.global.b32 \09%r18, [%rd110];\0A\09add.s64 \09%rd111, %rd146, %rd149;\0A\09ld.local.b32 \09%r19, [%rd111];\0A\09add.s64 \09%rd112, %rd144, %rd149;\0A\09ld.global.b32 \09%r20, [%rd112];\0A\09mul.wide.s32 \09%rd113, %r20, 4;\0A\09add.s64 \09%rd114, %rd148, %rd113;\0A\09ld.global.b32 \09%r21, [%rd114];\0A\09setp.lt.f32 \09%p16, %r18, 0f00800000;\0A\09mul.rn.f32 \09%r22, %r18, 0f4B000000;\0A\09selp.f32 \09%r23, %r22, %r18, %p16;\0A\09selp.f32 \09%r24, 0fC1B80000, 0f00000000, %p16;\0A\09add.s32 \09%r25, %r23, -1059760811;\0A\09and.b32 \09%r26, %r25, -8388608;\0A\09sub.s32 \09%r27, %r23, %r26;\0A\09cvt.rn.f32.s32 \09%r28, %r26;\0A\09fma.rn.f32 \09%r29, %r28, 0f34000000, %r24;\0A\09add.rn.f32 \09%r30, %r27, 0fBF800000;\0A\09fma.rn.f32 \09%r31, %r30, 0fBE055027, 0f3E1039F6;\0A\09fma.rn.f32 \09%r32, %r31, %r30, 0fBDF8CDCC;\0A\09fma.rn.f32 \09%r33, %r32, %r30, 0f3E0F2955;\0A\09fma.rn.f32 \09%r34, %r33, %r30, 0fBE2AD8B9;\0A\09fma.rn.f32 \09%r35, %r34, %r30, 0f3E4CED0B;\0A\09fma.rn.f32 \09%r36, %r35, %r30, 0fBE7FFF22;\0A\09fma.rn.f32 \09%r37, %r36, %r30, 0f3EAAAA78;\0A\09fma.rn.f32 \09%r38, %r37, %r30, 0fBF000000;\0A\09mul.rn.f32 \09%r39, %r30, %r38;\0A\09fma.rn.f32 \09%r40, %r39, %r30, %r30;\0A\09fma.rn.f32 \09%r41, %r29, 0f3F317218, %r40;\0A\09setp.gt.u32 \09%p17, %r23, 2139095039;\0A\09fma.rn.f32 \09%r42, %r23, 0f7F800000, 0f7F800000;\0A\09selp.f32 \09%r43, %r42, %r41, %p17;\0A\09setp.eq.f32 \09%p18, %r23, 0f00000000;\0A\09selp.f32 \09%r44, 0fFF800000, %r43, %p18;\0A\09add.rn.f32 \09%r45, %r19, %r44;\0A\09sub.rn.f32 \09%r46, %r45, %r21;\0A\09add.rn.f32 \09%r54, %r54, %r46;\0A\09add.s64 \09%rd150, %rd150, %rd91;\0A\09add.s64 \09%rd149, %rd149, %rd120;\0A\09add.s64 \09%rd148, %rd148, %rd117;\0A\09setp.lt.s64 \09%p19, %rd150, %rd94;\0A\09@%p19 bra \09$L__BB0_24;\0A\09add.s64 \09%rd147, %rd147, %rd91;\0A\09add.s64 \09%rd146, %rd146, %rd119;\0A\09add.s64 \09%rd145, %rd145, %rd46;\0A\09add.s64 \09%rd144, %rd144, %rd46;\0A\09add.s64 \09%rd143, %rd143, %rd116;\0A\09setp.lt.s64 \09%p20, %rd147, %rd94;\0A\09@%p20 bra \09$L__BB0_23;\0A\09bra.uni \09$L__BB0_26;\0A$L__BB0_28:\0A\09div.rn.f32 \09%r47, %r54, %r15;\0A\09atom.global.add.f32 \09%r48, [%rd2], %r47;\0A\09ret;\0A\0A}\0A\00", align 8
@main_kernel_0_module = internal global ptr null
@llvm.global_ctors = appending global [2 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 123, ptr @main_kernel_load, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main_kernel_0_load, ptr null }]
@llvm.global_dtors = appending global [2 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 123, ptr @main_kernel_unload, ptr null }, { i32, ptr, ptr } { i32 123, ptr @main_kernel_0_unload, ptr null }]
@main_kernel_main_kernel_name = private unnamed_addr constant [12 x i8] c"main_kernel\00", align 1
@main_kernel_0_main_kernel_name = private unnamed_addr constant [12 x i8] c"main_kernel\00", align 1

declare i32 @cudaMallocAsync(ptr, i64, ptr)

declare i32 @cudaMemsetAsync(ptr, i32, i64, ptr)

declare i32 @cudaMemcpyAsync(ptr, ptr, i64, i32, ptr)

declare i32 @cudaFreeAsync(ptr, ptr)

define void @main(ptr addrspace(1) %0, ptr addrspace(1) %1, i64 %2, i64 %3, i64 %4, i64 %5, i64 %6, i64 %7, i64 %8, ptr addrspace(1) %9, ptr addrspace(1) %10, i64 %11, i64 %12, i64 %13, i64 %14, i64 %15, ptr addrspace(1) %16, ptr addrspace(1) %17, i64 %18, i64 %19, i64 %20) {
  %22 = call ptr @mgpuStreamCreate()
  %23 = alloca ptr, align 8
  %24 = call i32 @cudaMallocAsync(ptr %23, i64 32768, ptr %22)
  %25 = load ptr, ptr %23, align 8
  %26 = alloca %0, align 8
  %27 = alloca ptr, i64 24, align 8
  %28 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 0
  store i64 128, ptr %28, align 4
  %29 = getelementptr ptr, ptr %27, i32 0
  store ptr %28, ptr %29, align 8
  %30 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 1
  store ptr %25, ptr %30, align 8
  %31 = getelementptr ptr, ptr %27, i32 1
  store ptr %30, ptr %31, align 8
  %32 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 2
  store ptr %25, ptr %32, align 8
  %33 = getelementptr ptr, ptr %27, i32 2
  store ptr %32, ptr %33, align 8
  %34 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 3
  store i64 0, ptr %34, align 4
  %35 = getelementptr ptr, ptr %27, i32 3
  store ptr %34, ptr %35, align 8
  %36 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 4
  store i64 8, ptr %36, align 4
  %37 = getelementptr ptr, ptr %27, i32 4
  store ptr %36, ptr %37, align 8
  %38 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 5
  store i64 1024, ptr %38, align 4
  %39 = getelementptr ptr, ptr %27, i32 5
  store ptr %38, ptr %39, align 8
  %40 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 6
  store i64 1024, ptr %40, align 4
  %41 = getelementptr ptr, ptr %27, i32 6
  store ptr %40, ptr %41, align 8
  %42 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 7
  store i64 1, ptr %42, align 4
  %43 = getelementptr ptr, ptr %27, i32 7
  store ptr %42, ptr %43, align 8
  %44 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 8
  store float 0xC7EFFFFFE0000000, ptr %44, align 4
  %45 = getelementptr ptr, ptr %27, i32 8
  store ptr %44, ptr %45, align 8
  %46 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 9
  store i64 0, ptr %46, align 4
  %47 = getelementptr ptr, ptr %27, i32 9
  store ptr %46, ptr %47, align 8
  %48 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 10
  store i64 1, ptr %48, align 4
  %49 = getelementptr ptr, ptr %27, i32 10
  store ptr %48, ptr %49, align 8
  %50 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 11
  store i64 8, ptr %50, align 4
  %51 = getelementptr ptr, ptr %27, i32 11
  store ptr %50, ptr %51, align 8
  %52 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 12
  store ptr addrspace(1) %0, ptr %52, align 8
  %53 = getelementptr ptr, ptr %27, i32 12
  store ptr %52, ptr %53, align 8
  %54 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 13
  store ptr addrspace(1) %1, ptr %54, align 8
  %55 = getelementptr ptr, ptr %27, i32 13
  store ptr %54, ptr %55, align 8
  %56 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 14
  store i64 %2, ptr %56, align 4
  %57 = getelementptr ptr, ptr %27, i32 14
  store ptr %56, ptr %57, align 8
  %58 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 15
  store i64 %3, ptr %58, align 4
  %59 = getelementptr ptr, ptr %27, i32 15
  store ptr %58, ptr %59, align 8
  %60 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 16
  store i64 %4, ptr %60, align 4
  %61 = getelementptr ptr, ptr %27, i32 16
  store ptr %60, ptr %61, align 8
  %62 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 17
  store i64 %5, ptr %62, align 4
  %63 = getelementptr ptr, ptr %27, i32 17
  store ptr %62, ptr %63, align 8
  %64 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 18
  store i64 %6, ptr %64, align 4
  %65 = getelementptr ptr, ptr %27, i32 18
  store ptr %64, ptr %65, align 8
  %66 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 19
  store i64 %7, ptr %66, align 4
  %67 = getelementptr ptr, ptr %27, i32 19
  store ptr %66, ptr %67, align 8
  %68 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 20
  store i64 %8, ptr %68, align 4
  %69 = getelementptr ptr, ptr %27, i32 20
  store ptr %68, ptr %69, align 8
  %70 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 21
  store i64 4, ptr %70, align 4
  %71 = getelementptr ptr, ptr %27, i32 21
  store ptr %70, ptr %71, align 8
  %72 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 22
  store i64 1536, ptr %72, align 4
  %73 = getelementptr ptr, ptr %27, i32 22
  store ptr %72, ptr %73, align 8
  %74 = getelementptr inbounds nuw %0, ptr %26, i32 0, i32 23
  store float 0.000000e+00, ptr %74, align 4
  %75 = getelementptr ptr, ptr %27, i32 23
  store ptr %74, ptr %75, align 8
  %76 = load ptr, ptr @main_kernel_module, align 8
  %77 = call ptr @mgpuModuleGetFunction(ptr %76, ptr @main_kernel_main_kernel_name)
  call void @mgpuLaunchKernel(ptr %77, i64 8, i64 1, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %22, ptr %27, ptr null, i64 24)
  %78 = alloca ptr, align 8
  %79 = call i32 @cudaMallocAsync(ptr %78, i64 4, ptr %22)
  %80 = load ptr, ptr %78, align 8
  %81 = alloca ptr, align 8
  %82 = call i32 @cudaMallocAsync(ptr %81, i64 4, ptr %22)
  %83 = load ptr, ptr %81, align 8
  call void @mgpuStreamSynchronize(ptr %22)
  call void @mgpuStreamDestroy(ptr %22)
  store float 0.000000e+00, ptr %83, align 4
  %84 = load float, ptr %83, align 4
  %85 = call ptr @mgpuStreamCreate()
  %86 = call i32 @cudaMemsetAsync(ptr %80, i32 0, i64 4, ptr %85)
  %87 = alloca %1, align 8
  %88 = alloca ptr, i64 35, align 8
  %89 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 0
  store i64 128, ptr %89, align 4
  %90 = getelementptr ptr, ptr %88, i32 0
  store ptr %89, ptr %90, align 8
  %91 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 1
  store float 0xFFF0000000000000, ptr %91, align 4
  %92 = getelementptr ptr, ptr %88, i32 1
  store ptr %91, ptr %92, align 8
  %93 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 2
  store i64 0, ptr %93, align 4
  %94 = getelementptr ptr, ptr %88, i32 2
  store ptr %93, ptr %94, align 8
  %95 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 3
  store i64 1, ptr %95, align 4
  %96 = getelementptr ptr, ptr %88, i32 3
  store ptr %95, ptr %96, align 8
  %97 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 4
  store i64 8, ptr %97, align 4
  %98 = getelementptr ptr, ptr %88, i32 4
  store ptr %97, ptr %98, align 8
  %99 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 5
  store ptr addrspace(1) %0, ptr %99, align 8
  %100 = getelementptr ptr, ptr %88, i32 5
  store ptr %99, ptr %100, align 8
  %101 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 6
  store ptr addrspace(1) %1, ptr %101, align 8
  %102 = getelementptr ptr, ptr %88, i32 6
  store ptr %101, ptr %102, align 8
  %103 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 7
  store i64 %2, ptr %103, align 4
  %104 = getelementptr ptr, ptr %88, i32 7
  store ptr %103, ptr %104, align 8
  %105 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 8
  store i64 %3, ptr %105, align 4
  %106 = getelementptr ptr, ptr %88, i32 8
  store ptr %105, ptr %106, align 8
  %107 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 9
  store i64 %4, ptr %107, align 4
  %108 = getelementptr ptr, ptr %88, i32 9
  store ptr %107, ptr %108, align 8
  %109 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 10
  store i64 %5, ptr %109, align 4
  %110 = getelementptr ptr, ptr %88, i32 10
  store ptr %109, ptr %110, align 8
  %111 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 11
  store i64 %6, ptr %111, align 4
  %112 = getelementptr ptr, ptr %88, i32 11
  store ptr %111, ptr %112, align 8
  %113 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 12
  store i64 %7, ptr %113, align 4
  %114 = getelementptr ptr, ptr %88, i32 12
  store ptr %113, ptr %114, align 8
  %115 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 13
  store i64 %8, ptr %115, align 4
  %116 = getelementptr ptr, ptr %88, i32 13
  store ptr %115, ptr %116, align 8
  %117 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 14
  store i64 4, ptr %117, align 4
  %118 = getelementptr ptr, ptr %88, i32 14
  store ptr %117, ptr %118, align 8
  %119 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 15
  store i64 1536, ptr %119, align 4
  %120 = getelementptr ptr, ptr %88, i32 15
  store ptr %119, ptr %120, align 8
  %121 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 16
  store float %84, ptr %121, align 4
  %122 = getelementptr ptr, ptr %88, i32 16
  store ptr %121, ptr %122, align 8
  %123 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 17
  store ptr %25, ptr %123, align 8
  %124 = getelementptr ptr, ptr %88, i32 17
  store ptr %123, ptr %124, align 8
  %125 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 18
  store ptr %25, ptr %125, align 8
  %126 = getelementptr ptr, ptr %88, i32 18
  store ptr %125, ptr %126, align 8
  %127 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 19
  store i64 0, ptr %127, align 4
  %128 = getelementptr ptr, ptr %88, i32 19
  store ptr %127, ptr %128, align 8
  %129 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 20
  store i64 8, ptr %129, align 4
  %130 = getelementptr ptr, ptr %88, i32 20
  store ptr %129, ptr %130, align 8
  %131 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 21
  store i64 1024, ptr %131, align 4
  %132 = getelementptr ptr, ptr %88, i32 21
  store ptr %131, ptr %132, align 8
  %133 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 22
  store i64 1024, ptr %133, align 4
  %134 = getelementptr ptr, ptr %88, i32 22
  store ptr %133, ptr %134, align 8
  %135 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 23
  store i64 1, ptr %135, align 4
  %136 = getelementptr ptr, ptr %88, i32 23
  store ptr %135, ptr %136, align 8
  %137 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 24
  store ptr addrspace(1) %9, ptr %137, align 8
  %138 = getelementptr ptr, ptr %88, i32 24
  store ptr %137, ptr %138, align 8
  %139 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 25
  store ptr addrspace(1) %10, ptr %139, align 8
  %140 = getelementptr ptr, ptr %88, i32 25
  store ptr %139, ptr %140, align 8
  %141 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 26
  store i64 %11, ptr %141, align 4
  %142 = getelementptr ptr, ptr %88, i32 26
  store ptr %141, ptr %142, align 8
  %143 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 27
  store i64 %12, ptr %143, align 4
  %144 = getelementptr ptr, ptr %88, i32 27
  store ptr %143, ptr %144, align 8
  %145 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 28
  store i64 %13, ptr %145, align 4
  %146 = getelementptr ptr, ptr %88, i32 28
  store ptr %145, ptr %146, align 8
  %147 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 29
  store i64 %14, ptr %147, align 4
  %148 = getelementptr ptr, ptr %88, i32 29
  store ptr %147, ptr %148, align 8
  %149 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 30
  store i64 %15, ptr %149, align 4
  %150 = getelementptr ptr, ptr %88, i32 30
  store ptr %149, ptr %150, align 8
  %151 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 31
  store float 8.192000e+03, ptr %151, align 4
  %152 = getelementptr ptr, ptr %88, i32 31
  store ptr %151, ptr %152, align 8
  %153 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 32
  store ptr %80, ptr %153, align 8
  %154 = getelementptr ptr, ptr %88, i32 32
  store ptr %153, ptr %154, align 8
  %155 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 33
  store ptr %80, ptr %155, align 8
  %156 = getelementptr ptr, ptr %88, i32 33
  store ptr %155, ptr %156, align 8
  %157 = getelementptr inbounds nuw %1, ptr %87, i32 0, i32 34
  store i64 0, ptr %157, align 4
  %158 = getelementptr ptr, ptr %88, i32 34
  store ptr %157, ptr %158, align 8
  %159 = load ptr, ptr @main_kernel_0_module, align 8
  %160 = call ptr @mgpuModuleGetFunction(ptr %159, ptr @main_kernel_0_main_kernel_name)
  call void @mgpuLaunchKernel(ptr %160, i64 8, i64 1, i64 1, i64 1, i64 1, i64 1, i32 0, ptr %85, ptr %88, ptr null, i64 35)
  %161 = addrspacecast ptr addrspace(1) %17 to ptr
  %162 = call i32 @cudaMemcpyAsync(ptr %161, ptr %80, i64 4, i32 3, ptr %85)
  %163 = call i32 @cudaFreeAsync(ptr %25, ptr %85)
  %164 = call i32 @cudaFreeAsync(ptr %80, ptr %85)
  %165 = call i32 @cudaFreeAsync(ptr %83, ptr %85)
  call void @mgpuStreamSynchronize(ptr %85)
  call void @mgpuStreamDestroy(ptr %85)
  ret void
}

define void @_mlir_ciface_main_impl(ptr %0, ptr %1, ptr %2) {
  %4 = load { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] }, ptr %0, align 8
  %5 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 0
  %6 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 1
  %7 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 2
  %8 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 3, 0
  %9 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 3, 1
  %10 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 3, 2
  %11 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 4, 0
  %12 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 4, 1
  %13 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [3 x i64], [3 x i64] } %4, 4, 2
  %14 = load { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] }, ptr %1, align 8
  %15 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 0
  %16 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 1
  %17 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 2
  %18 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 3, 0
  %19 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 3, 1
  %20 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 4, 0
  %21 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [2 x i64], [2 x i64] } %14, 4, 1
  %22 = load { ptr addrspace(1), ptr addrspace(1), i64, [1 x i64], [1 x i64] }, ptr %2, align 8
  %23 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [1 x i64], [1 x i64] } %22, 0
  %24 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [1 x i64], [1 x i64] } %22, 1
  %25 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [1 x i64], [1 x i64] } %22, 2
  %26 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [1 x i64], [1 x i64] } %22, 3, 0
  %27 = extractvalue { ptr addrspace(1), ptr addrspace(1), i64, [1 x i64], [1 x i64] } %22, 4, 0
  call void @main(ptr addrspace(1) %5, ptr addrspace(1) %6, i64 %7, i64 %8, i64 %9, i64 %10, i64 %11, i64 %12, i64 %13, ptr addrspace(1) %15, ptr addrspace(1) %16, i64 %17, i64 %18, i64 %19, i64 %20, i64 %21, ptr addrspace(1) %23, ptr addrspace(1) %24, i64 %25, i64 %26, i64 %27)
  ret void
}

define void @_mlir_ciface_main(ptr %0, ptr %1) {
  %3 = load ptr, ptr %1, align 8
  %4 = getelementptr ptr, ptr %1, i32 1
  %5 = load ptr, ptr %4, align 8
  call void @_mlir_ciface_main_impl(ptr %0, ptr %3, ptr %5)
  ret void
}

declare ptr @mgpuStreamCreate()

declare void @mgpuStreamSynchronize(ptr)

declare void @mgpuStreamDestroy(ptr)

define internal void @main_kernel_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main_kernel_binary, i32 3)
  store ptr %0, ptr @main_kernel_module, align 8
  ret void
}

declare ptr @mgpuModuleLoadJIT(ptr, i32)

define internal void @main_kernel_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main_kernel_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

declare void @mgpuModuleUnload(ptr)

define internal void @main_kernel_0_load() section ".text.startup" {
entry:
  %0 = call ptr @mgpuModuleLoadJIT(ptr @main_kernel_0_binary, i32 3)
  store ptr %0, ptr @main_kernel_0_module, align 8
  ret void
}

define internal void @main_kernel_0_unload() section ".text.startup" {
entry:
  %0 = load ptr, ptr @main_kernel_0_module, align 8
  call void @mgpuModuleUnload(ptr %0)
  ret void
}

declare ptr @mgpuModuleGetFunction(ptr, ptr)

declare void @mgpuLaunchKernel(ptr, i64, i64, i64, i64, i64, i64, i32, ptr, ptr, ptr, i64)

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
