// Pipeline integration test: matmul + bias add (non-aligned: 100x300 x 300x200)
//
// Runs the full pipeline with canonicalization + CSE between each pass:
//   1. nova-tile-and-distribute   — workgroup tiling via scf.forall
//   2. canonicalize + cse         — fold affine.min/max, clean up
//   3. nova-gpu-pad-operands      — pad A/B/C to static multiples of 128
//   4. canonicalize + cse         — fold fill+pad, clean up pads
//
// This verifies that padding fires correctly AFTER workgroup tiling and that
// the cleanup patterns (ExtractSliceOfPadTensorSwap, FoldFillIntoPad) work.

func.func @pipeline_test(%A: tensor<100x300xf32>,
                          %B: tensor<300x200xf32>,
                          %bias: tensor<100x200xf32>) -> tensor<100x200xf32> {
  %cst = arith.constant 0.0 : f32
  %empty = tensor.empty() : tensor<100x200xf32>
  // Zero-init output for matmul — FoldFillIntoPad should fold this with the
  // output pad generated by nova-gpu-pad-operands.
  %C = linalg.fill ins(%cst : f32) outs(%empty : tensor<100x200xf32>) -> tensor<100x200xf32>

  // Root op: matmul — will be tiled to workgroups and padded.
  %matmul = linalg.matmul ins(%A, %B : tensor<100x300xf32>, tensor<300x200xf32>)
                          outs(%C : tensor<100x200xf32>) -> tensor<100x200xf32>

  // Consumer: bias add — will be fused into the forall loop.
  %out = tensor.empty() : tensor<100x200xf32>
  %result = linalg.generic {
    indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>,
                     affine_map<(d0, d1) -> (d0, d1)>,
                     affine_map<(d0, d1) -> (d0, d1)>],
    iterator_types = ["parallel", "parallel"]
  } ins(%matmul, %bias : tensor<100x200xf32>, tensor<100x200xf32>)
    outs(%out : tensor<100x200xf32>) {
  ^bb0(%m: f32, %b: f32, %o: f32):
    %add = arith.addf %m, %b : f32
    linalg.yield %add : f32
  } -> tensor<100x200xf32>

  return %result : tensor<100x200xf32>
}
